-- Canonical React-WP schema. server.mjs and api/install-schema.ts both execute this file,
-- so it is the single source of truth for a fresh installation.

create extension if not exists pgcrypto;

-- Tables ----------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'subscriber'
    check (role in ('administrator', 'editor', 'author', 'contributor', 'subscriber', 'super_admin')),
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft' check (status in ('draft', 'published')),
  is_post boolean not null default false,
  category_id uuid references public.categories(id) on delete set null,
  featured_category_id uuid references public.categories(id) on delete set null,
  posts_limit integer not null default 6 check (posts_limit > 0),
  display_layout varchar(20) not null default 'grid' check (display_layout in ('grid', 'list')),
  layout varchar(20) not null default 'boxed' check (layout in ('boxed', 'wide', 'full')),
  show_sidebar boolean not null default false,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex boolean not null default false,
  og_title text,
  og_description text,
  og_image text,
  twitter_card varchar(30) not null default 'summary_large_image',
  comments_open boolean not null default true,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_id bigint references public.pages(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  -- References profiles, not auth.users, so PostgREST can embed the author in one request.
  author_id uuid references public.profiles(id) on delete cascade,
  author_name text,
  author_email text,
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists comments_page_id_idx on public.comments(page_id);
create index if not exists comments_parent_id_idx on public.comments(parent_id);

create table if not exists public.options (
  option_name text primary key,
  option_value text not null
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  location text not null default 'primary',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.plugins (
  plugin_id text primary key,
  name text not null,
  version text not null,
  author text,
  description text default '',
  folder text,
  source text not null default 'bundled',
  active boolean not null default false,
  installed_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  title varchar(255),
  alt_text text,
  url text not null,
  provider varchar(50) not null default 'external'
    check (provider in ('cloudinary', 'imagekit', 'external')),
  file_name varchar(255),
  -- Cloudinary public_id / ImageKit fileId. Deleting the asset at the provider needs this.
  provider_file_id text,
  width integer,
  height integer,
  bytes bigint,
  mime_type varchar(100),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.media add column if not exists provider_file_id text;

-- Roles and capabilities ------------------------------------------------------
-- Roles live here rather than in auth.users.raw_user_meta_data, which users can
-- rewrite themselves via supabase.auth.updateUser().

-- The role comes from the default_user_role option, never from the sign-up payload, which
-- is attacker-controlled. Administrator and super_admin are rejected outright.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  configured text;
begin
  select option_value into configured
  from public.options
  where option_name = 'default_user_role';

  if configured not in ('subscriber', 'contributor', 'author', 'editor') then
    configured := 'subscriber';
  end if;

  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)),
    configured
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, email, display_name)
select u.id, u.email, split_part(u.email, '@', 1) from auth.users u
on conflict (id) do nothing;

-- security definer so policies can read profiles without recursing through its own RLS.
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.user_has_cap(capability text)
returns boolean language sql stable security definer set search_path = public as $$
  select case public.current_user_role()
    when 'super_admin' then true
    when 'administrator' then true
    when 'editor' then capability in (
      'read', 'edit_posts', 'delete_posts', 'publish_posts', 'upload_files',
      'edit_others_posts', 'delete_others_posts', 'edit_pages', 'publish_pages',
      'manage_categories', 'moderate_comments')
    when 'author' then capability in ('read', 'edit_posts', 'delete_posts', 'publish_posts', 'upload_files')
    when 'contributor' then capability in ('read', 'edit_posts', 'delete_posts')
    when 'subscriber' then capability = 'read'
    else false
  end;
$$;

grant execute on function public.current_user_role() to anon, authenticated;
grant execute on function public.user_has_cap(text) to anon, authenticated;

-- A trigger rather than a policy: RLS WITH CHECK cannot reliably compare the old and
-- new role within a single statement.
create or replace function public.profiles_guard_role()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.role is distinct from old.role then
    -- auth.uid() is null for the installer and service-role connections.
    if auth.uid() is null then
      return new;
    end if;
    if public.current_user_role() not in ('administrator', 'super_admin') then
      raise exception 'Only administrators can change user roles.';
    end if;
    if new.id = auth.uid() then
      raise exception 'You cannot change your own role.';
    end if;
  end if;
  new.updated_at := timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists profiles_guard_role_trigger on public.profiles;
create trigger profiles_guard_role_trigger
  before update on public.profiles
  for each row execute function public.profiles_guard_role();

-- Row level security ----------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.categories enable row level security;
alter table public.pages enable row level security;
alter table public.comments enable row level security;
alter table public.options enable row level security;
alter table public.menus enable row level security;
alter table public.plugins enable row level security;
alter table public.media enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
  on public.profiles for select to authenticated using (true);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "Administrators can update any profile" on public.profiles;
create policy "Administrators can update any profile"
  on public.profiles for update to authenticated
  using (public.user_has_cap('edit_users')) with check (public.user_has_cap('edit_users'));

drop policy if exists "Public can read published pages" on public.pages;
drop policy if exists "Authenticated users can manage pages" on public.pages;
drop policy if exists "Readers can see published or own pages" on public.pages;
create policy "Readers can see published or own pages"
  on public.pages for select to anon, authenticated
  using (status = 'published' or author_id = auth.uid() or public.user_has_cap('edit_others_posts'));
drop policy if exists "Contributors can create content" on public.pages;
create policy "Contributors can create content"
  on public.pages for insert to authenticated
  with check (
    public.user_has_cap('edit_posts')
    and (status = 'draft' or public.user_has_cap('publish_posts'))
  );
drop policy if exists "Authors edit own content, editors edit all" on public.pages;
create policy "Authors edit own content, editors edit all"
  on public.pages for update to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('edit_posts'))
    or public.user_has_cap('edit_others_posts')
  )
  with check (status = 'draft' or public.user_has_cap('publish_posts'));
drop policy if exists "Authors delete own content, editors delete all" on public.pages;
create policy "Authors delete own content, editors delete all"
  on public.pages for delete to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('delete_posts'))
    or public.user_has_cap('delete_others_posts')
  );

drop policy if exists "Public can read published posts" on public.posts;
drop policy if exists "Administrators and editors manage posts" on public.posts;
drop policy if exists "Authors and contributors manage own posts" on public.posts;
drop policy if exists "Authenticated users can manage posts" on public.posts;
drop policy if exists "Readers can see published or own posts" on public.posts;
create policy "Readers can see published or own posts"
  on public.posts for select to anon, authenticated
  using (status = 'published' or author_id = auth.uid() or public.user_has_cap('edit_others_posts'));
drop policy if exists "Capability-based post writes" on public.posts;
create policy "Capability-based post writes"
  on public.posts for all to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('edit_posts'))
    or public.user_has_cap('edit_others_posts')
  )
  with check (
    public.user_has_cap('edit_posts')
    and (status = 'draft' or public.user_has_cap('publish_posts'))
  );

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
  on public.categories for select to anon, authenticated using (true);
drop policy if exists "Authenticated users can manage categories" on public.categories;
drop policy if exists "Category managers can write categories" on public.categories;
create policy "Category managers can write categories"
  on public.categories for all to authenticated
  using (public.user_has_cap('manage_categories'))
  with check (public.user_has_cap('manage_categories'));

-- Commenting is for signed-in users. The author comes from the session, not the request
-- body, so a comment cannot be attributed to someone else.
drop policy if exists "Authenticated users can manage comments" on public.comments;
drop policy if exists "Public can read approved comments" on public.comments;
create policy "Public can read approved comments"
  on public.comments for select to anon, authenticated
  using (status = 'approved' or author_id = auth.uid() or public.user_has_cap('moderate_comments'));
drop policy if exists "Anyone can submit a comment" on public.comments;
drop policy if exists "Members can submit comments" on public.comments;
create policy "Members can submit comments"
  on public.comments for insert to authenticated
  with check (author_id = auth.uid() and status in ('pending', 'approved'));
drop policy if exists "Moderators can manage comments" on public.comments;
create policy "Moderators can manage comments"
  on public.comments for update to authenticated
  using (public.user_has_cap('moderate_comments')) with check (public.user_has_cap('moderate_comments'));
drop policy if exists "Moderators can delete comments" on public.comments;
drop policy if exists "Moderators and authors can delete comments" on public.comments;
create policy "Moderators and authors can delete comments"
  on public.comments for delete to authenticated
  using (public.user_has_cap('moderate_comments') or author_id = auth.uid());

-- Options stay publicly readable: the public site needs site_title and menu_links.
drop policy if exists "Allow public read access on options" on public.options;
create policy "Allow public read access on options"
  on public.options for select using (true);
drop policy if exists "Allow authenticated full access on options" on public.options;
drop policy if exists "Settings managers can write options" on public.options;
create policy "Settings managers can write options"
  on public.options for all to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Authenticated users can manage menus" on public.menus;
drop policy if exists "Public can read menus" on public.menus;
create policy "Public can read menus"
  on public.menus for select to anon, authenticated using (true);
drop policy if exists "Settings managers can write menus" on public.menus;
create policy "Settings managers can write menus"
  on public.menus for all to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Authenticated users can manage plugins" on public.plugins;
drop policy if exists "Public can read plugins" on public.plugins;
create policy "Public can read plugins"
  on public.plugins for select to anon, authenticated using (true);
drop policy if exists "Plugin managers can write plugins" on public.plugins;
create policy "Plugin managers can write plugins"
  on public.plugins for all to authenticated
  using (public.user_has_cap('activate_plugins'))
  with check (public.user_has_cap('activate_plugins'));

drop policy if exists "Public can read media" on public.media;
create policy "Public can read media"
  on public.media for select to anon, authenticated using (true);
drop policy if exists "Uploaders can add media" on public.media;
create policy "Uploaders can add media"
  on public.media for insert to authenticated
  with check (public.user_has_cap('upload_files'));
drop policy if exists "Uploaders can update media" on public.media;
create policy "Uploaders can update media"
  on public.media for update to authenticated
  using (public.user_has_cap('upload_files')) with check (public.user_has_cap('upload_files'));
drop policy if exists "Uploaders can delete media" on public.media;
create policy "Uploaders can delete media"
  on public.media for delete to authenticated
  using (public.user_has_cap('upload_files'));
