-- Canonical React-WP schema. server.mjs and api/install-schema.ts both execute this file,
-- so it is the single source of truth for a fresh installation.

create extension if not exists pgcrypto;

-- Tables ----------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'subscriber'
    check (role in ('administrator', 'shop_manager', 'editor', 'author', 'contributor', 'subscriber', 'super_admin')),
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft' check (status in ('draft', 'published', 'trash')),
  is_post boolean not null default false,
  category_id uuid references public.categories(id) on delete set null,
  featured_category_id uuid references public.categories(id) on delete set null,
  posts_limit integer not null default 6 check (posts_limit > 0),
  display_layout varchar(20) not null default 'grid' check (display_layout in ('grid', 'list')),
  layout varchar(20) not null default 'boxed' check (layout in ('boxed', 'wide', 'full')),
  show_sidebar boolean not null default false,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex boolean not null default false,
  og_title text,
  og_description text,
  og_image text,
  twitter_card varchar(30) not null default 'summary_large_image',
  comments_open boolean not null default true,
  meta_keywords text,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Page editor: meta keywords (shown only when enabled under App Settings Ã¢â€ â€™ SEO).
alter table public.pages add column if not exists meta_keywords text;

-- 'trash' was added by 20260926_bulk_actions_trash.sql; older installs have the inline check without it.
alter table public.pages drop constraint if exists pages_status_check;
alter table public.pages add constraint pages_status_check check (status in ('draft', 'published', 'trash'));

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_id bigint references public.pages(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  -- References profiles, not auth.users, so PostgREST can embed the author in one request.
  author_id uuid references public.profiles(id) on delete cascade,
  author_name text,
  author_email text,
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists comments_page_id_idx on public.comments(page_id);
create index if not exists comments_parent_id_idx on public.comments(parent_id);

create table if not exists public.options (
  option_name text primary key,
  option_value text not null
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  location text not null default 'primary',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.plugins (
  plugin_id text primary key,
  name text not null,
  version text not null,
  author text,
  description text default '',
  folder text,
  source text not null default 'bundled',
  active boolean not null default false,
  installed_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  title varchar(255),
  alt_text text,
  url text not null,
  provider varchar(50) not null default 'external'
    check (provider in ('cloudinary', 'imagekit', 'external')),
  file_name varchar(255),
  -- Cloudinary public_id / ImageKit fileId. Deleting the asset at the provider needs this.
  provider_file_id text,
  width integer,
  height integer,
  bytes bigint,
  mime_type varchar(100),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.media add column if not exists provider_file_id text;

-- Media Library folders (20260927_media_folders.sql). Paths like "general" or "blog/2026".
alter table public.media add column if not exists folder varchar(255) not null default 'general';
alter table public.media drop constraint if exists media_folder_format;
alter table public.media add constraint media_folder_format
  check (folder ~ '^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$' and char_length(folder) <= 255);
create index if not exists idx_media_folder on public.media (folder);

-- Per-user disk quota overrides (App Settings Ã¢â€ â€™ Uploads). Keyed by email rather than profile
-- id so an allowance can be set before the person signs up, and not stored on profiles because
-- users can update their own profile row. Private: options is public, this table is not.
create table if not exists public.rwp_quota_overrides (
  email text primary key check (email = lower(email) and position('@' in email) > 1),
  quota_mb integer not null check (quota_mb >= 0),
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Roles and capabilities ------------------------------------------------------
-- Roles live here rather than in auth.users.raw_user_meta_data, which users can
-- rewrite themselves via supabase.auth.updateUser().

-- The role comes from the default_user_role option, never from the sign-up payload, which
-- is attacker-controlled. Administrator and super_admin are rejected outright.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  configured text;
begin
  select option_value into configured
  from public.options
  where option_name = 'default_user_role';

  -- "null not in (...)" is null, not true, so a missing option must be checked explicitly.
  if configured is null or configured not in ('subscriber', 'contributor', 'author', 'editor') then
    configured := 'subscriber';
  end if;

  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)),
    configured
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, email, display_name)
select u.id, u.email, split_part(u.email, '@', 1) from auth.users u
on conflict (id) do nothing;

-- security definer so policies can read profiles without recursing through its own RLS.
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

-- App Settings live in one JSON option, rwp_app_settings. Invalid JSON must not break every
-- capability check on the site, so it reads as an empty document instead of raising.
create or replace function public.rwp_app_settings()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  raw text;
begin
  select option_value into raw from public.options where option_name = 'rwp_app_settings';
  if raw is null or raw = '' then
    return '{}'::jsonb;
  end if;
  begin
    return coalesce(raw::jsonb, '{}'::jsonb);
  exception when others then
    return '{}'::jsonb;
  end;
end;
$$;

-- A number at a path in the settings document, or null when unset or not a number.
create or replace function public.rwp_app_setting_number(p_path text[])
returns numeric language sql stable security definer set search_path = public as $$
  select case
    when jsonb_typeof(public.rwp_app_settings() #> p_path) = 'number'
      then (public.rwp_app_settings() #>> p_path)::numeric
  end;
$$;

-- Mirrors roleCapabilities + applyCapabilityGrants in src/lib/roles.ts. Only the four grants
-- below can be switched on from App Settings; nothing above Author can be granted this way.
create or replace function public.user_has_cap(capability text)
returns boolean language sql stable security definer set search_path = public as $$
  select case public.current_user_role()
    when 'super_admin' then true
    when 'administrator' then true
    when 'shop_manager' then capability in (
      'read', 'edit_posts', 'delete_posts', 'publish_posts', 'upload_files',
      'edit_others_posts', 'delete_others_posts', 'edit_pages', 'publish_pages',
      'manage_categories', 'moderate_comments', 'manage_shop', 'list_users')
    when 'editor' then capability in (
      'read', 'edit_posts', 'delete_posts', 'publish_posts', 'upload_files',
      'edit_others_posts', 'delete_others_posts', 'edit_pages', 'publish_pages',
      'manage_categories', 'moderate_comments')
    when 'author' then capability in ('read', 'edit_posts', 'delete_posts', 'publish_posts', 'upload_files')
    when 'contributor' then capability in ('read', 'edit_posts', 'delete_posts')
      or (capability = 'upload_files'
        and coalesce(public.rwp_app_settings() #> '{roles,contributor_upload_files}' = 'true'::jsonb, false))
      or (capability = 'publish_posts'
        and coalesce(public.rwp_app_settings() #> '{roles,contributor_publish_posts}' = 'true'::jsonb, false))
    when 'subscriber' then capability = 'read'
      or (capability = 'upload_files'
        and coalesce(public.rwp_app_settings() #> '{roles,subscriber_upload_files}' = 'true'::jsonb, false))
      or (capability in ('edit_posts', 'delete_posts')
        and coalesce(public.rwp_app_settings() #> '{roles,subscriber_edit_posts}' = 'true'::jsonb, false))
    else false
  end;
$$;

grant execute on function public.current_user_role() to anon, authenticated;
grant execute on function public.user_has_cap(text) to anon, authenticated;

-- A trigger rather than a policy: RLS WITH CHECK cannot reliably compare the old and
-- new role within a single statement.
create or replace function public.profiles_guard_role()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.role is distinct from old.role then
    -- auth.uid() is null for the installer and service-role connections.
    if auth.uid() is null then
      return new;
    end if;
    if public.current_user_role() not in ('administrator', 'super_admin') then
      raise exception 'Only administrators can change user roles.';
    end if;
    if new.id = auth.uid() then
      raise exception 'You cannot change your own role.';
    end if;
  end if;
  new.updated_at := timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists profiles_guard_role_trigger on public.profiles;
create trigger profiles_guard_role_trigger
  before update on public.profiles
  for each row execute function public.profiles_guard_role();

-- Disk quotas and media rules (App Settings Ã¢â€ â€™ Uploads) --------------------------------------

-- Bytes the user may store, or null for unlimited. An override by email wins; otherwise the
-- role's quota applies (Shop Manager uses the Editor quota). Administrators are unlimited
-- unless they have an override.
create or replace function public.rwp_user_quota_bytes(p_user uuid)
returns bigint language plpgsql stable security definer set search_path = public as $$
declare
  user_email text;
  user_role text;
  override_mb integer;
  role_mb numeric;
begin
  select lower(u.email), p.role into user_email, user_role
  from auth.users u left join public.profiles p on p.id = u.id
  where u.id = p_user;

  select quota_mb into override_mb from public.rwp_quota_overrides where email = user_email;
  if found then
    return override_mb::bigint * 1048576;
  end if;

  if user_role = 'shop_manager' then
    user_role := 'editor';
  end if;
  if user_role is null or user_role not in ('editor', 'author', 'contributor', 'subscriber') then
    return null;
  end if;

  role_mb := public.rwp_app_setting_number(array['uploads', 'quota_mb', user_role]);
  return case when role_mb is null or role_mb < 0 then null else (role_mb * 1048576)::bigint end;
end;
$$;

-- What the signed-in user has used and may still upload, for the media screen and the
-- ImageKit signing endpoint.
create or replace function public.rwp_upload_allowance()
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'can_upload', coalesce(public.user_has_cap('upload_files'), false),
    'used_bytes', (select coalesce(sum(m.bytes), 0) from public.media m where auth.uid() is not null and m.uploaded_by = auth.uid()),
    'quota_bytes', case when auth.uid() is null then 0 else public.rwp_user_quota_bytes(auth.uid()) end,
    'has_override', exists (
      select 1 from public.rwp_quota_overrides o join auth.users u on lower(u.email) = o.email
      where u.id = auth.uid()
    )
  );
$$;

-- Disk usage of every account, for App Settings Ã¢â€ â€™ Uploads.
create or replace function public.rwp_disk_usage_report()
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  if not public.user_has_cap('manage_options') then
    raise exception 'Only administrators can view disk usage. It needs the manage_options capability, and your role does not have it.'
      using errcode = '42501';
  end if;
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
      'email', lower(coalesce(u.email, p.email)),
      'display_name', p.display_name,
      'role', p.role,
      'used_bytes', (select coalesce(sum(m.bytes), 0) from public.media m where m.uploaded_by = p.id),
      'quota_bytes', public.rwp_user_quota_bytes(p.id)
    ) order by lower(coalesce(u.email, p.email))), '[]'::jsonb)
    from public.profiles p left join auth.users u on u.id = p.id
  );
end;
$$;

-- Whether the signed-in user may edit or delete a media row uploaded by p_uploaded_by. With
-- general.scope_media_to_owner on, roles without edit_others_posts manage only their own.
-- Used by the media policies and by /api/media-delete, so both apply the same rule.
create or replace function public.rwp_can_manage_media(p_uploaded_by uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.user_has_cap('upload_files'), false) and (
    (auth.uid() is not null and p_uploaded_by = auth.uid())
    or public.user_has_cap('edit_others_posts')
    or coalesce(public.rwp_app_settings() #> '{general,scope_media_to_owner}' <> 'true'::jsonb, true)
  );
$$;

-- The size, dimension and quota values checked here are reported by the uploading browser,
-- because the file goes straight to Cloudinary or ImageKit. This stops honest clients and
-- keeps the library and quota accounting consistent; it is not a hard limit on what reaches
-- the provider. It also pins uploaded_by to the caller, so quota and scoping cannot be dodged
-- by attributing an upload to someone else.
create or replace function public.media_enforce_upload_rules()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  caller uuid := auth.uid();
  max_kb numeric;
  min_w numeric;
  min_h numeric;
  max_w numeric;
  max_h numeric;
  quota bigint;
  used bigint;
begin
  -- Installer, service-role and SQL Editor connections have no auth.uid().
  if caller is null then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    -- Only title and alt text are meant to change after upload.
    new.uploaded_by := old.uploaded_by;
    new.bytes := old.bytes;
    new.width := old.width;
    new.height := old.height;
    return new;
  end if;

  new.uploaded_by := caller;
  if new.provider = 'external' then
    return new;
  end if;

  max_kb := public.rwp_app_setting_number('{uploads,max_upload_kb}');
  quota := public.rwp_user_quota_bytes(caller);
  if (max_kb is not null or quota is not null) and new.bytes is null then
    raise exception 'Upload rejected: the file size is missing, and upload limits are enabled under App Settings Ã¢â€ â€™ Uploads.';
  end if;
  if max_kb is not null and new.bytes > max_kb * 1024 then
    raise exception 'Upload rejected: this file is % KB, over the % KB limit set under App Settings Ã¢â€ â€™ Uploads.',
      ceil(new.bytes / 1024.0), max_kb;
  end if;

  if coalesce(new.mime_type, '') like 'image/%' then
    min_w := public.rwp_app_setting_number('{uploads,min_width}');
    min_h := public.rwp_app_setting_number('{uploads,min_height}');
    max_w := public.rwp_app_setting_number('{uploads,max_width}');
    max_h := public.rwp_app_setting_number('{uploads,max_height}');
    if coalesce(min_w, min_h, max_w, max_h) is not null and (new.width is null or new.height is null) then
      raise exception 'Upload rejected: the image dimensions are missing, and dimension limits are enabled under App Settings Ã¢â€ â€™ Uploads.';
    end if;
    if new.width < min_w or new.height < min_h then
      raise exception 'Upload rejected: the image is % Ãƒâ€” % px, smaller than the minimum of % Ãƒâ€” % px.',
        new.width, new.height, coalesce(min_w::text, 'any'), coalesce(min_h::text, 'any');
    end if;
    if new.width > max_w or new.height > max_h then
      raise exception 'Upload rejected: the image is % Ãƒâ€” % px, larger than the maximum of % Ãƒâ€” % px.',
        new.width, new.height, coalesce(max_w::text, 'any'), coalesce(max_h::text, 'any');
    end if;
  end if;

  if quota is not null then
    -- Serialises one user's concurrent uploads so two cannot both fit into the last megabyte.
    perform pg_advisory_xact_lock(hashtext('rwp_media_quota:' || caller::text));
    select coalesce(sum(bytes), 0) into used from public.media where uploaded_by = caller;
    if used + new.bytes > quota then
      raise exception 'Upload rejected: this file needs % MB, but you have % MB left of your % MB disk quota.',
        round(new.bytes / 1048576.0, 2), round(greatest(quota - used, 0) / 1048576.0, 2), round(quota / 1048576.0, 2);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists media_enforce_upload_rules on public.media;
create trigger media_enforce_upload_rules
  before insert or update on public.media
  for each row execute function public.media_enforce_upload_rules();

-- Internal helpers are executable by anon by default; only the endpoints below are meant to
-- be called. rwp_can_manage_media stays callable because the media policies run it as the
-- signed-in user and /api/media-delete calls it over REST.
revoke execute on function public.rwp_app_settings() from public, anon, authenticated;
revoke execute on function public.rwp_app_setting_number(text[]) from public, anon, authenticated;
revoke execute on function public.rwp_user_quota_bytes(uuid) from public, anon, authenticated;
revoke execute on function public.media_enforce_upload_rules() from public, anon, authenticated;
revoke execute on function public.rwp_upload_allowance() from public, anon;
revoke execute on function public.rwp_disk_usage_report() from public, anon;
revoke execute on function public.rwp_can_manage_media(uuid) from public, anon;
grant execute on function public.rwp_upload_allowance() to authenticated;
grant execute on function public.rwp_disk_usage_report() to authenticated;
grant execute on function public.rwp_can_manage_media(uuid) to authenticated;

-- Row level security ----------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.categories enable row level security;
alter table public.pages enable row level security;
alter table public.comments enable row level security;
alter table public.options enable row level security;
alter table public.menus enable row level security;
alter table public.plugins enable row level security;
alter table public.media enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
  on public.profiles for select to authenticated using (true);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "Administrators can update any profile" on public.profiles;
create policy "Administrators can update any profile"
  on public.profiles for update to authenticated
  using (public.user_has_cap('edit_users')) with check (public.user_has_cap('edit_users'));

drop policy if exists "Public can read published pages" on public.pages;
drop policy if exists "Authenticated users can manage pages" on public.pages;
drop policy if exists "Readers can see published or own pages" on public.pages;
create policy "Readers can see published or own pages"
  on public.pages for select to anon, authenticated
  using (status = 'published' or author_id = auth.uid() or public.user_has_cap('edit_others_posts'));
drop policy if exists "Contributors can create content" on public.pages;
create policy "Contributors can create content"
  on public.pages for insert to authenticated
  with check (
    public.user_has_cap('edit_posts')
    and (status in ('draft', 'trash') or public.user_has_cap('publish_posts'))
  );
drop policy if exists "Authors edit own content, editors edit all" on public.pages;
create policy "Authors edit own content, editors edit all"
  on public.pages for update to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('edit_posts'))
    or public.user_has_cap('edit_others_posts')
  )
  with check (status in ('draft', 'trash') or public.user_has_cap('publish_posts'));
drop policy if exists "Authors delete own content, editors delete all" on public.pages;
create policy "Authors delete own content, editors delete all"
  on public.pages for delete to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('delete_posts'))
    or public.user_has_cap('delete_others_posts')
  );

drop policy if exists "Public can read published posts" on public.posts;
drop policy if exists "Administrators and editors manage posts" on public.posts;
drop policy if exists "Authors and contributors manage own posts" on public.posts;
drop policy if exists "Authenticated users can manage posts" on public.posts;
drop policy if exists "Readers can see published or own posts" on public.posts;
create policy "Readers can see published or own posts"
  on public.posts for select to anon, authenticated
  using (status = 'published' or author_id = auth.uid() or public.user_has_cap('edit_others_posts'));
drop policy if exists "Capability-based post writes" on public.posts;
create policy "Capability-based post writes"
  on public.posts for all to authenticated
  using (
    (author_id = auth.uid() and public.user_has_cap('edit_posts'))
    or public.user_has_cap('edit_others_posts')
  )
  with check (
    public.user_has_cap('edit_posts')
    and (status = 'draft' or public.user_has_cap('publish_posts'))
  );

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
  on public.categories for select to anon, authenticated using (true);
drop policy if exists "Authenticated users can manage categories" on public.categories;
drop policy if exists "Category managers can write categories" on public.categories;
create policy "Category managers can write categories"
  on public.categories for all to authenticated
  using (public.user_has_cap('manage_categories'))
  with check (public.user_has_cap('manage_categories'));

-- Commenting is for signed-in users. The author comes from the session, not the request
-- body, so a comment cannot be attributed to someone else.
drop policy if exists "Authenticated users can manage comments" on public.comments;
drop policy if exists "Public can read approved comments" on public.comments;
create policy "Public can read approved comments"
  on public.comments for select to anon, authenticated
  using (status = 'approved' or author_id = auth.uid() or public.user_has_cap('moderate_comments'));
drop policy if exists "Anyone can submit a comment" on public.comments;
drop policy if exists "Members can submit comments" on public.comments;
create policy "Members can submit comments"
  on public.comments for insert to authenticated
  with check (author_id = auth.uid() and status in ('pending', 'approved'));
drop policy if exists "Moderators can manage comments" on public.comments;
create policy "Moderators can manage comments"
  on public.comments for update to authenticated
  using (public.user_has_cap('moderate_comments')) with check (public.user_has_cap('moderate_comments'));
drop policy if exists "Moderators can delete comments" on public.comments;
drop policy if exists "Moderators and authors can delete comments" on public.comments;
create policy "Moderators and authors can delete comments"
  on public.comments for delete to authenticated
  using (public.user_has_cap('moderate_comments') or author_id = auth.uid());

-- Options stay publicly readable: the public site needs site_title and menu_links.
drop policy if exists "Allow public read access on options" on public.options;
create policy "Allow public read access on options"
  on public.options for select using (true);
drop policy if exists "Allow authenticated full access on options" on public.options;
drop policy if exists "Settings managers can write options" on public.options;
create policy "Settings managers can write options"
  on public.options for all to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Authenticated users can manage menus" on public.menus;
drop policy if exists "Public can read menus" on public.menus;
create policy "Public can read menus"
  on public.menus for select to anon, authenticated using (true);
drop policy if exists "Settings managers can write menus" on public.menus;
create policy "Settings managers can write menus"
  on public.menus for all to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Authenticated users can manage plugins" on public.plugins;
drop policy if exists "Public can read plugins" on public.plugins;
create policy "Public can read plugins"
  on public.plugins for select to anon, authenticated using (true);
drop policy if exists "Plugin managers can write plugins" on public.plugins;
create policy "Plugin managers can write plugins"
  on public.plugins for all to authenticated
  using (public.user_has_cap('activate_plugins'))
  with check (public.user_has_cap('activate_plugins'));

drop policy if exists "Public can read media" on public.media;
create policy "Public can read media"
  on public.media for select to anon, authenticated using (true);
drop policy if exists "Uploaders can add media" on public.media;
create policy "Uploaders can add media"
  on public.media for insert to authenticated
  with check (public.user_has_cap('upload_files'));
drop policy if exists "Uploaders can update media" on public.media;
create policy "Uploaders can update media"
  on public.media for update to authenticated
  using (public.rwp_can_manage_media(uploaded_by)) with check (public.rwp_can_manage_media(uploaded_by));
drop policy if exists "Uploaders can delete media" on public.media;
create policy "Uploaders can delete media"
  on public.media for delete to authenticated
  using (public.rwp_can_manage_media(uploaded_by));

-- Media folder manager (20260928_media_folder_manager.sql): folders as rows, created by the
-- media_record_folder trigger or from the Media Library; renamed/deleted by the invoker functions.
create table if not exists public.media_folders (
  path varchar(255) primary key
    constraint media_folders_path_format check (path ~ '^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$' and char_length(path) <= 255),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

-- "blog/2026/may" -> blog, blog/2026, blog/2026/may. Called by the invoker functions below,
-- so authenticated users need execute; it only splits a string.
create or replace function public.rwp_media_folder_lineage(p_path text)
returns setof text language sql immutable set search_path = public as $$
  select array_to_string((string_to_array(p_path, '/'))[1:depth], '/')
  from generate_series(1, coalesce(array_length(string_to_array(p_path, '/'), 1), 0)) as depth;
$$;
revoke execute on function public.rwp_media_folder_lineage(text) from public, anon;
grant execute on function public.rwp_media_folder_lineage(text) to authenticated;

-- True when p_folder is p_root or inside it. LIKE is avoided because "_" is a wildcard there.
create or replace function public.rwp_media_folder_in(p_folder text, p_root text)
returns boolean language sql immutable set search_path = public as $$
  select p_folder = p_root or left(p_folder, char_length(p_root) + 1) = p_root || '/';
$$;
revoke execute on function public.rwp_media_folder_in(text, text) from public, anon;
grant execute on function public.rwp_media_folder_in(text, text) to authenticated;

-- Backfill: the default folder plus every folder media already uses, with its parents.
insert into public.media_folders (path, created_by)
select distinct lineage, null::uuid
from (
  select 'general'::text as folder
  union
  select distinct folder from public.media
) used
cross join lateral public.rwp_media_folder_lineage(used.folder) as lineage
on conflict (path) do nothing;

-- Keeps media_folders in step with media.folder. SECURITY DEFINER because it writes folder rows
-- the caller's own RLS may not cover; the path is already validated by media_folder_format.
create or replace function public.media_record_folder()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.media_folders (path, created_by)
  select lineage, auth.uid() from public.rwp_media_folder_lineage(new.folder) as lineage
  on conflict (path) do nothing;
  return new;
end;
$$;
revoke execute on function public.media_record_folder() from public, anon, authenticated;

drop trigger if exists media_record_folder on public.media;
create trigger media_record_folder
  after insert or update of folder on public.media
  for each row execute function public.media_record_folder();

alter table public.media_folders enable row level security;

drop policy if exists "Uploaders can read media folders" on public.media_folders;
create policy "Uploaders can read media folders"
  on public.media_folders for select to authenticated using (true);
drop policy if exists "Uploaders can create media folders" on public.media_folders;
create policy "Uploaders can create media folders"
  on public.media_folders for insert to authenticated
  with check (public.user_has_cap('upload_files'));
-- Same ownership rule as media: your own folders, or everyone's when media is not limited to
-- its uploader (or you have edit_others_posts). rwp_can_manage_media() only exists once
-- 20260920_app_settings.sql has been run, so this looks it up when called rather than when the
-- policy is created: before that migration any uploader may manage any media (the same as the
-- media policies then), and afterwards the ownership rule applies without re-running this file.
-- PL/pgSQL resolves the call on first execution, which is what makes the lookup safe.
create or replace function public.rwp_can_manage_media_folder(p_created_by uuid)
returns boolean language plpgsql stable security invoker set search_path = public as $$
begin
  if not coalesce(public.user_has_cap('upload_files'), false) then
    return false;
  end if;
  -- Folders with no creator (backfilled from existing media) are shared.
  if p_created_by is null then
    return true;
  end if;
  if to_regprocedure('public.rwp_can_manage_media(uuid)') is null then
    return true;
  end if;
  return public.rwp_can_manage_media(p_created_by);
end;
$$;
revoke execute on function public.rwp_can_manage_media_folder(uuid) from public, anon;
grant execute on function public.rwp_can_manage_media_folder(uuid) to authenticated;

-- The media inside a folder stays protected by the media policies, because renaming or deleting
-- a non-empty folder has to update those rows too. The default folder is never deleted.
drop policy if exists "Uploaders can delete media folders" on public.media_folders;
create policy "Uploaders can delete media folders"
  on public.media_folders for delete to authenticated
  using (path <> 'general' and public.rwp_can_manage_media_folder(created_by));

-- Rename / move a folder --------------------------------------------------------------------------
create or replace function public.rwp_rename_media_folder(p_from text, p_to text)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  src text := trim(both '/' from coalesce(p_from, ''));
  dst text := trim(both '/' from coalesce(p_to, ''));
  total integer;
  moved integer;
  folder_total integer;
  folder_removed integer;
begin
  if not public.user_has_cap('upload_files') then
    raise exception using errcode = '42501', message = 'Renaming folders needs the upload_files capability.';
  end if;
  if src = 'general' then
    raise exception 'The "general" folder is where new media goes by default, so it cannot be renamed.';
  end if;
  if dst !~ '^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$' or char_length(dst) > 255 then
    raise exception 'The folder name "%" is not valid. Use letters, digits, "-" and "_", with "/" between levels.', dst;
  end if;
  if src = dst then
    return jsonb_build_object('moved', 0);
  end if;
  if public.rwp_media_folder_in(dst, src) then
    raise exception 'The folder "%" cannot be moved inside itself ("%").', src, dst;
  end if;
  if not exists (select 1 from public.media_folders where public.rwp_media_folder_in(path, src))
     and not exists (select 1 from public.media where public.rwp_media_folder_in(folder, src)) then
    raise exception 'The folder "%" does not exist. Reload the Media Library.', src;
  end if;

  -- Media rows are readable by everyone, so this counts items the caller may not be able to change.
  select count(*) into total from public.media where public.rwp_media_folder_in(folder, src);
  update public.media
  set folder = dst || substr(folder, char_length(src) + 1)
  where public.rwp_media_folder_in(folder, src);
  get diagnostics moved = row_count;
  if moved < total then
    raise exception using errcode = '42501', message = format(
      'The folder "%s" was not renamed: %s of its %s items were uploaded by someone else, and your role can only change its own media (Settings Ã¢â€ â€™ General limits media to its uploader). Nothing was changed.',
      src, total - moved, total);
  end if;

  -- Carry empty subfolders over, then remove the old paths.
  insert into public.media_folders (path)
  select distinct lineage
  from public.media_folders f
  cross join lateral public.rwp_media_folder_lineage(dst || substr(f.path, char_length(src) + 1)) as lineage
  where public.rwp_media_folder_in(f.path, src)
  on conflict (path) do nothing;

  select count(*) into folder_total from public.media_folders where public.rwp_media_folder_in(path, src);
  delete from public.media_folders where public.rwp_media_folder_in(path, src);
  get diagnostics folder_removed = row_count;
  if folder_removed < folder_total then
    raise exception using errcode = '42501', message = format(
      'The folder "%s" was not renamed: it contains folders created by someone else, which your role cannot remove. Nothing was changed.', src);
  end if;

  return jsonb_build_object('moved', moved, 'folder', dst);
end;
$$;
revoke execute on function public.rwp_rename_media_folder(text, text) from public, anon;
grant execute on function public.rwp_rename_media_folder(text, text) to authenticated;

-- Delete a folder -----------------------------------------------------------------------------------
-- With p_move_to, the folder's media (including subfolders) moves there first. Without it, the
-- folder must be empty: deleting the media itself goes through /api/media-delete, because the
-- files also have to be removed at Cloudinary or ImageKit.
create or replace function public.rwp_delete_media_folder(p_path text, p_move_to text default null)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  target text := trim(both '/' from coalesce(p_path, ''));
  dst text := nullif(trim(both '/' from coalesce(p_move_to, '')), '');
  total integer;
  moved integer := 0;
  folder_total integer;
  folder_removed integer;
begin
  if not public.user_has_cap('upload_files') then
    raise exception using errcode = '42501', message = 'Deleting folders needs the upload_files capability.';
  end if;
  if target = 'general' then
    raise exception 'The "general" folder is where new media goes by default, so it cannot be deleted.';
  end if;

  select count(*) into total from public.media where public.rwp_media_folder_in(folder, target);
  if total > 0 then
    if dst is null then
      raise exception 'The folder "%" still holds % item(s). Move them to another folder or delete them first.', target, total;
    end if;
    if dst !~ '^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$' or char_length(dst) > 255 then
      raise exception 'The folder name "%" is not valid. Use letters, digits, "-" and "_", with "/" between levels.', dst;
    end if;
    if public.rwp_media_folder_in(dst, target) then
      raise exception 'Media cannot be moved into "%", because that folder is being deleted.', dst;
    end if;
    update public.media set folder = dst where public.rwp_media_folder_in(folder, target);
    get diagnostics moved = row_count;
    if moved < total then
      raise exception using errcode = '42501', message = format(
        'The folder "%s" was not deleted: %s of its %s items were uploaded by someone else, and your role can only change its own media. Nothing was changed.',
        target, total - moved, total);
    end if;
  end if;

  select count(*) into folder_total from public.media_folders where public.rwp_media_folder_in(path, target);
  delete from public.media_folders where public.rwp_media_folder_in(path, target);
  get diagnostics folder_removed = row_count;
  if folder_removed < folder_total then
    raise exception using errcode = '42501', message = format(
      'The folder "%s" was not deleted: it contains folders created by someone else, which your role cannot remove. Nothing was changed.', target);
  end if;

  return jsonb_build_object('moved', moved, 'folders', folder_removed);
end;
$$;
revoke execute on function public.rwp_delete_media_folder(text, text) from public, anon;
grant execute on function public.rwp_delete_media_folder(text, text) to authenticated;

alter table public.rwp_quota_overrides enable row level security;
drop policy if exists "Settings managers manage quota overrides" on public.rwp_quota_overrides;
create policy "Settings managers manage quota overrides"
  on public.rwp_quota_overrides for all to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));


-- Builder layout columns. These live on a core table and core writes them itself
-- (rwp_install_default_content, builder_create_site_template), so they are part of the
-- core schema even though only the page builder plugin fills them in.
alter table public.pages add column if not exists builder_data jsonb;
alter table public.pages add column if not exists is_builder_enabled boolean not null default false;

-- Site templates (Page Builder -> Templates) and default content.
-- Kept identical to supabase/migrations/20260925_site_templates.sql, minus its column renames from 20260924.

alter table public.pages add column if not exists is_site_template boolean not null default false;
alter table public.pages add column if not exists template_type varchar(50);

-- The 20260924 objects refer to the old column names.
drop trigger if exists builder_guard_shop_page on public.pages;
drop function if exists public.builder_guard_shop_page();
drop function if exists public.builder_create_shop_page(text, text, jsonb);
alter table public.pages drop constraint if exists pages_shop_page_type_check;
drop index if exists public.pages_shop_page_type_key;

create or replace function public.rwp_template_types()
returns text[] language sql immutable set search_path = public as $$
  select array[
    'header', 'footer', 'single_post', 'page', '404', 'search',
    'archive', 'archive_category', 'archive_author', 'archive_date',
    'shop', 'product', 'product_category', 'cart', 'checkout', 'my_account'
  ];
$$;

alter table public.pages drop constraint if exists pages_template_type_check;
alter table public.pages add constraint pages_template_type_check check (
  (not is_site_template and template_type is null)
  or (is_site_template and template_type = any(public.rwp_template_types()))
);

create unique index if not exists pages_template_type_key
  on public.pages (template_type) where template_type is not null;

-- Guard ----------------------------------------------------------------------------------------------

create or replace function public.builder_guard_site_template()
returns trigger language plpgsql set search_path = public as $$
begin
  -- The SQL Editor, service role and restores without a session are not restricted.
  if auth.uid() is null then
    return new;
  end if;
  if (new.is_site_template
      or (tg_op = 'UPDATE' and (old.is_site_template or old.template_type is distinct from new.template_type)))
     and not public.user_has_cap('manage_shop') then
    raise exception using
      errcode = '42501',
      message = 'Site templates (header, footer, single post, archives, shop screensÃ¢â‚¬Â¦) can only be created or edited by Administrators and Shop Managers (the manage_shop capability).';
  end if;
  return new;
end;
$$;

drop trigger if exists builder_guard_site_template on public.pages;
create trigger builder_guard_site_template
  before insert or update on public.pages
  for each row execute function public.builder_guard_site_template();

-- Create one template -------------------------------------------------------------------------------

-- A free slug starting with p_base: p_base, p_base-2, p_base-3Ã¢â‚¬Â¦ (Invoker: sees only what the caller can.)
create or replace function public.rwp_free_slug(p_base text)
returns text language plpgsql stable set search_path = public as $$
declare
  v_slug text := p_base;
  v_n integer := 1;
begin
  while exists (select 1 from public.pages where slug = v_slug) loop
    v_n := v_n + 1;
    v_slug := p_base || '-' || v_n;
  end loop;
  return v_slug;
end;
$$;

-- Returns the type's page id, creating it the first time. Security invoker, so the insert goes
-- through the pages RLS (publishing needs publish_posts) and the guard trigger above.
create or replace function public.builder_create_site_template(p_type text, p_title text, p_builder_data jsonb, p_status text default 'draft')
returns bigint language plpgsql set search_path = public as $$
declare
  v_id bigint;
begin
  if p_type is null or not (p_type = any(public.rwp_template_types())) then
    raise exception using errcode = '22023', message = format('Unknown template type "%s".', p_type);
  end if;
  if coalesce(p_status, 'draft') not in ('draft', 'published') then
    raise exception using errcode = '22023', message = format('Unknown status "%s": use draft or published.', p_status);
  end if;
  if not public.user_has_cap('manage_shop') then
    raise exception using
      errcode = '42501',
      message = 'Creating a site template needs the manage_shop capability (Administrator or Shop Manager).';
  end if;

  select id into v_id from public.pages where template_type = p_type;
  if v_id is not null then
    return v_id;
  end if;

  insert into public.pages (title, slug, status, is_site_template, template_type, builder_data, is_builder_enabled,
                            author_id, noindex, comments_open)
  values (coalesce(nullif(trim(p_title), ''), p_type), public.rwp_free_slug('template-' || replace(p_type, '_', '-')),
          coalesce(p_status, 'draft'), true, p_type,
          coalesce(p_builder_data, '{"version":1,"settings":{},"content":[]}'::jsonb), true,
          auth.uid(), true, false)
  on conflict (template_type) where template_type is not null do nothing
  returning id into v_id;

  if v_id is null then
    select id into v_id from public.pages where template_type = p_type;
  end if;
  return v_id;
end;
$$;

-- Default content -----------------------------------------------------------------------------------

-- p_items: [{ "key": "home", "title": "Home", "slug": "home", "template_type": null | "header",
--             "content": "<p>Ã¢â‚¬Â¦</p>", "builder_data": {Ã¢â‚¬Â¦} | null }]
-- Items whose slug or template type already exists are skipped. With p_reading, the created
-- "home" and "blog" items become the front page and posts page, but only when both are unset.
-- Returns { installed: bool, created: [{ key, id }] }.
create or replace function public.rwp_install_default_content(p_group text, p_items jsonb, p_reading boolean default false)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_done jsonb;
  v_item jsonb;
  v_type text;
  v_slug text;
  v_id bigint;
  v_created jsonb := '[]'::jsonb;
  v_home bigint;
  v_blog bigint;
begin
  if p_group not in ('site', 'shop') then
    raise exception using errcode = '22023', message = format('Unknown default content group "%s".', p_group);
  end if;
  if auth.uid() is null then
    raise exception using errcode = '42501', message = 'Installing default content needs a signed-in user.';
  end if;
  if p_group = 'site' and not public.user_has_cap('manage_options') then
    raise exception using errcode = '42501', message = 'Installing the default site pages needs an Administrator (manage_options).';
  end if;
  if not public.user_has_cap('manage_shop') then
    raise exception using errcode = '42501', message = 'Installing default templates needs an Administrator or Shop Manager (manage_shop).';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception using errcode = '22023', message = 'Default content items must be a JSON array.';
  end if;

  -- One install per group, even when two admins open the dashboard at once.
  perform pg_advisory_xact_lock(hashtext('rwp_install_default_content'));
  select coalesce((select option_value::jsonb from public.options where option_name = 'rwp_default_content'), '[]'::jsonb) into v_done;
  if v_done ? p_group then
    return jsonb_build_object('installed', false, 'created', '[]'::jsonb);
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_type := nullif(v_item ->> 'template_type', '');
    v_slug := nullif(trim(v_item ->> 'slug'), '');
    if v_type is not null and not (v_type = any(public.rwp_template_types())) then
      raise exception using errcode = '22023', message = format('Unknown template type "%s" in default content.', v_type);
    end if;
    if p_group = 'shop' and (v_type is null or v_type not in ('shop', 'product', 'product_category', 'cart', 'checkout', 'my_account')) then
      raise exception using errcode = '22023', message = 'The shop default content may only contain shop templates.';
    end if;
    if v_type is null and v_slug is null then
      raise exception using errcode = '22023', message = 'A default page needs a slug.';
    end if;
    if (v_type is not null and exists (select 1 from public.pages where template_type = v_type))
       or (v_type is null and exists (select 1 from public.pages where slug = v_slug)) then
      continue;
    end if;

    -- Runs as the definer, so the Custom HTML and template guards still see auth.uid() of the caller.
    insert into public.pages (title, slug, content, status, is_post, is_site_template, template_type,
                              builder_data, is_builder_enabled, author_id, noindex, comments_open)
    values (
      coalesce(nullif(trim(v_item ->> 'title'), ''), coalesce(v_type, v_slug)),
      case when v_type is not null then public.rwp_free_slug('template-' || replace(v_type, '_', '-')) else v_slug end,
      coalesce(v_item ->> 'content', ''),
      'published', false, v_type is not null, v_type,
      case when jsonb_typeof(v_item -> 'builder_data') = 'object' then v_item -> 'builder_data' else null end,
      jsonb_typeof(v_item -> 'builder_data') = 'object',
      auth.uid(), v_type is not null, false
    )
    returning id into v_id;
    v_created := v_created || jsonb_build_object('key', v_item ->> 'key', 'id', v_id);
    if v_item ->> 'key' = 'home' then v_home := v_id; end if;
    if v_item ->> 'key' = 'blog' then v_blog := v_id; end if;
  end loop;

  if p_reading and v_home is not null and v_blog is not null
     and coalesce((select option_value from public.options where option_name = 'home_page_id'), '') = ''
     and coalesce((select option_value from public.options where option_name = 'posts_page_id'), '') = '' then
    insert into public.options (option_name, option_value) values ('home_page_id', v_home::text)
      on conflict (option_name) do update set option_value = excluded.option_value;
    insert into public.options (option_name, option_value) values ('posts_page_id', v_blog::text)
      on conflict (option_name) do update set option_value = excluded.option_value;
  end if;

  insert into public.options (option_name, option_value) values ('rwp_default_content', (v_done || to_jsonb(p_group))::text)
    on conflict (option_name) do update set option_value = excluded.option_value;

  return jsonb_build_object('installed', true, 'created', v_created);
end;
$$;

revoke execute on function public.builder_guard_site_template() from public, anon, authenticated;
revoke execute on function public.rwp_free_slug(text) from public, anon;
grant execute on function public.rwp_free_slug(text) to authenticated;
revoke execute on function public.builder_create_site_template(text, text, jsonb, text) from public, anon;
revoke execute on function public.rwp_install_default_content(text, jsonb, boolean) from public, anon;
grant execute on function public.builder_create_site_template(text, text, jsonb, text) to authenticated;
grant execute on function public.rwp_install_default_content(text, jsonb, boolean) to authenticated;

-- Backup and restore (Settings -> Backup) ------------------------------------------------
-- Kept identical to supabase/migrations/20260919_backup_restore.sql.

-- Every table in public except profiles is backed up, so tables added by later migrations
-- or plugins are included without touching this file. profiles is special: its rows belong
-- to auth.users accounts, which a backup cannot recreate (it never contains passwords).
-- Accounts are matched by email on restore instead.

create or replace function public.rwp_backup_export()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  table_row record;
  table_rows jsonb;
  tables jsonb := '{}'::jsonb;
begin
  if not public.user_has_cap('manage_options') then
    raise exception 'Only administrators can export a backup. It needs the manage_options capability, and your role does not have it.'
      using errcode = '42501';
  end if;

  for table_row in
    select c.relname
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relname <> 'profiles'
    order by c.relname
  loop
    execute format('select coalesce(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) from public.%I t', table_row.relname)
      into table_rows;
    tables := tables || jsonb_build_object(table_row.relname, table_rows);
  end loop;

  return jsonb_build_object(
    'format', 'react-wp-backup',
    'version', 1,
    'created_at', timezone('utc'::text, now()),
    'tables', tables,
    'users', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', p.id,
        'email', coalesce(u.email, p.email),
        'display_name', p.display_name,
        'avatar_url', p.avatar_url,
        'bio', p.bio,
        'role', p.role
      )), '[]'::jsonb)
      from public.profiles p
      left join auth.users u on u.id = p.id
    )
  );
end;
$$;

-- Replaces every backed-up table with the backup's rows, in one transaction: if any row
-- fails, nothing is changed. User references (columns with a foreign key to profiles or
-- auth.users) are re-pointed to the account with the same email on this site, or cleared.
create or replace function public.rwp_backup_import(p_backup jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  backup_tables jsonb := p_backup -> 'tables';
  backup_users jsonb := coalesce(p_backup -> 'users', '[]'::jsonb);
  user_map jsonb;
  pending text[];
  ready text[];
  ordered text[] := '{}';
  table_name text;
  table_rows jsonb;
  column_list text;
  ref record;
  identity_col record;
  inserted bigint;
  dropped bigint;
  counts jsonb := '{}'::jsonb;
  warnings jsonb := '[]'::jsonb;
  unmatched jsonb;
  installed_value text;
begin
  if not public.user_has_cap('manage_options') then
    raise exception 'Only administrators can restore a backup. It needs the manage_options capability, and your role does not have it.'
      using errcode = '42501';
  end if;
  if p_backup ->> 'format' is distinct from 'react-wp-backup' then
    raise exception 'This file is not a React-WP backup (its "format" field is missing or wrong).';
  end if;
  if coalesce((p_backup ->> 'version')::int, 0) <> 1 then
    raise exception 'This backup uses format version %, but this site only understands version 1. Update this site to the version that made the backup.',
      coalesce(p_backup ->> 'version', 'none');
  end if;
  if jsonb_typeof(backup_tables) is distinct from 'object' then
    raise exception 'The backup has no "tables" object, so there is nothing to restore.';
  end if;
  if jsonb_typeof(backup_users) <> 'array' then
    raise exception 'The backup''s "users" field must be an array.';
  end if;

  -- Old account id -> this site's account id, matched by email.
  select coalesce(jsonb_object_agg(bu ->> 'id', u.id), '{}'::jsonb) into user_map
  from jsonb_array_elements(backup_users) bu
  join auth.users u on lower(u.email) = lower(bu ->> 'email')
  where bu ->> 'id' is not null;

  select jsonb_agg(bu ->> 'email' order by bu ->> 'email') into unmatched
  from jsonb_array_elements(backup_users) bu
  where not (user_map ? (bu ->> 'id'));
  if unmatched is not null then
    warnings := warnings || jsonb_build_array(format(
      '%s account(s) in the backup have no account with the same email on this site, so their content was kept without an author: %s. Once they sign up, reassign their content by hand.',
      jsonb_array_length(unmatched),
      (select string_agg(value, ', ') from jsonb_array_elements_text(unmatched))
    ));
  end if;

  -- Profile details for matched accounts. Your own role is never changed, so a restore cannot
  -- lock you out, and only a super admin can hand out super_admin.
  update public.profiles p set
    display_name = coalesce(bu ->> 'display_name', p.display_name),
    avatar_url = bu ->> 'avatar_url',
    bio = bu ->> 'bio',
    role = case
      when p.id = auth.uid() then p.role
      when bu ->> 'role' in ('administrator', 'shop_manager', 'editor', 'author', 'contributor', 'subscriber') then bu ->> 'role'
      when bu ->> 'role' = 'super_admin' and public.current_user_role() = 'super_admin' then 'super_admin'
      else p.role
    end
  from jsonb_array_elements(backup_users) bu
  where user_map ->> (bu ->> 'id') = p.id::text;

  -- Restore order: a table goes after the tables its foreign keys point to.
  pending := array(
    select c.relname::text
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relname <> 'profiles'
  );
  while cardinality(pending) > 0 loop
    ready := array(
      select t from unnest(pending) t
      where not exists (
        select 1 from pg_constraint con
        join pg_class ref_table on ref_table.oid = con.confrelid
        join pg_namespace ref_ns on ref_ns.oid = ref_table.relnamespace
        where con.contype = 'f'
          and con.conrelid = format('public.%I', t)::regclass
          and con.confrelid <> con.conrelid
          and ref_ns.nspname = 'public'
          and ref_table.relname = any(pending)
      )
    );
    if cardinality(ready) = 0 then
      raise exception 'These tables reference each other in a cycle, so no restore order exists: %', array_to_string(pending, ', ');
    end if;
    ordered := ordered || ready;
    pending := array(select unnest(pending) except select unnest(ready));
  end loop;

  for table_name in
    select key from jsonb_object_keys(backup_tables) key
    where key <> 'profiles' and not (key = any(ordered))
  loop
    warnings := warnings || jsonb_build_array(format(
      'The backup has a table "%s" that this database does not have, so it was skipped. Run the missing migrations in supabase/migrations/ and restore again to include it.',
      table_name));
  end loop;

  select option_value into installed_value from public.options where option_name = 'installed';

  execute 'truncate table ' || (select string_agg(format('public.%I', t), ', ') from unnest(ordered) t) || ' restart identity';

  foreach table_name in array ordered loop
    table_rows := backup_tables -> table_name;
    counts := counts || jsonb_build_object(table_name, 0);
    continue when table_rows is null or jsonb_typeof(table_rows) <> 'array' or jsonb_array_length(table_rows) = 0;

    for ref in
      select a.attname::text as col, a.attnotnull as required
      from pg_constraint con
      join pg_attribute a on a.attrelid = con.conrelid and a.attnum = con.conkey[1]
      where con.contype = 'f'
        and con.conrelid = format('public.%I', table_name)::regclass
        and con.confrelid in ('public.profiles'::regclass, 'auth.users'::regclass)
        and cardinality(con.conkey) = 1
    loop
      select coalesce(jsonb_agg(case
          when r ? ref.col then r || jsonb_build_object(ref.col, user_map -> (r ->> ref.col))
          else r
        end), '[]'::jsonb)
      into table_rows
      from jsonb_array_elements(table_rows) r;

      if ref.required then
        select count(*) into dropped from jsonb_array_elements(table_rows) r where r -> ref.col = 'null'::jsonb;
        if dropped > 0 then
          select coalesce(jsonb_agg(r), '[]'::jsonb) into table_rows
          from jsonb_array_elements(table_rows) r where r -> ref.col is distinct from 'null'::jsonb;
          warnings := warnings || jsonb_build_array(format(
            '%s row(s) of %s were skipped because they belong to accounts that do not exist on this site.',
            dropped, table_name));
        end if;
      end if;
    end loop;
    continue when jsonb_array_length(table_rows) = 0;

    -- Only columns both the backup and this table have, so an older backup still restores
    -- and newer columns take their defaults.
    select string_agg(format('%I', a.attname), ', ' order by a.attnum) into column_list
    from pg_attribute a
    where a.attrelid = format('public.%I', table_name)::regclass
      and a.attnum > 0 and not a.attisdropped and a.attgenerated = ''
      and (table_rows -> 0) ? a.attname;
    continue when column_list is null;

    -- Triggers are off while the rows go in: they would stamp new timestamps, write extra
    -- builder revisions, re-run stock and review bookkeeping, and the backup already holds
    -- the results of all of that.
    execute format('alter table public.%I disable trigger user', table_name);
    begin
      execute format(
        'insert into public.%1$I (%2$s) overriding system value select %2$s from jsonb_populate_recordset(null::public.%1$I, $1)',
        table_name, column_list)
      using table_rows;
      get diagnostics inserted = row_count;
    exception when others then
      raise exception 'Restoring table "%" failed: %', table_name, sqlerrm using errcode = sqlstate;
    end;
    execute format('alter table public.%I enable trigger user', table_name);
    counts := counts || jsonb_build_object(table_name, inserted);

    for identity_col in
      select a.attname::text as col, pg_get_serial_sequence(format('public.%I', table_name), a.attname) as seq
      from pg_attribute a
      where a.attrelid = format('public.%I', table_name)::regclass and a.attnum > 0 and not a.attisdropped
        and pg_get_serial_sequence(format('public.%I', table_name), a.attname) is not null
    loop
      execute format('select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)',
        identity_col.seq, identity_col.col, table_name);
    end loop;
  end loop;

  -- The installed flag describes this database, not the one the backup came from.
  if installed_value is not null then
    insert into public.options (option_name, option_value) values ('installed', installed_value)
    on conflict (option_name) do update set option_value = excluded.option_value;
  end if;

  return jsonb_build_object(
    'counts', counts,
    'warnings', warnings,
    'users_matched', (select count(*) from jsonb_object_keys(user_map)),
    'users_unmatched', coalesce(jsonb_array_length(unmatched), 0)
  );
end;
$$;

-- New public functions are executable by anon by default; both check manage_options
-- themselves, but anon has no reason to reach them at all.
revoke execute on function public.rwp_backup_export() from public, anon;
revoke execute on function public.rwp_backup_import(jsonb) from public, anon;
grant execute on function public.rwp_backup_export() to authenticated;
grant execute on function public.rwp_backup_import(jsonb) to authenticated;

-- Optional profile details (Admin Ã¢â€ â€™ Profile Ã¢â€ â€™ More about you) --------------------------------------
-- Kept identical to supabase/migrations/20260921_profile_details.sql.
--
-- A separate table, not more columns on profiles, for two reasons:
--   * profiles is readable by every signed-in user (it drives author names and the Users
--     screen), and a phone number or birth date must not be. This table is readable only by
--     the person themselves and by roles with list_users.
--   * rwp_backup_export() skips profiles but backs up every other public table, and its
--     restore re-points id (a foreign key to profiles) by email. So these rows are backed up
--     and restored with no change to the backup functions.
--
-- Everything is optional. The Dashboard's setup checklist only suggests filling it in.

create table if not exists public.profile_details (
  id uuid primary key references public.profiles(id) on delete cascade,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.profile_details add column if not exists first_name text;
alter table public.profile_details add column if not exists last_name text;
alter table public.profile_details add column if not exists pronouns text;
alter table public.profile_details add column if not exists job_title text;
alter table public.profile_details add column if not exists company text;
alter table public.profile_details add column if not exists website text;
alter table public.profile_details add column if not exists location text;
alter table public.profile_details add column if not exists timezone text;
alter table public.profile_details add column if not exists phone text;
alter table public.profile_details add column if not exists birth_date date;
alter table public.profile_details add column if not exists social_links jsonb not null default '{}'::jsonb;

-- Dropped first so a re-run replaces them instead of failing on "already exists".
alter table public.profile_details drop constraint if exists profile_details_lengths_check;
alter table public.profile_details add constraint profile_details_lengths_check check (
  char_length(coalesce(first_name, '')) <= 100
  and char_length(coalesce(last_name, '')) <= 100
  and char_length(coalesce(pronouns, '')) <= 40
  and char_length(coalesce(job_title, '')) <= 120
  and char_length(coalesce(company, '')) <= 120
  and char_length(coalesce(website, '')) <= 300
  and char_length(coalesce(location, '')) <= 120
  and char_length(coalesce(timezone, '')) <= 60
  and char_length(coalesce(phone, '')) <= 40
);

-- Websites are rendered as links, so only http(s) URLs: no javascript: URLs.
alter table public.profile_details drop constraint if exists profile_details_website_check;
alter table public.profile_details add constraint profile_details_website_check
  check (website is null or website ~* '^https?://[^\s]+$');

alter table public.profile_details drop constraint if exists profile_details_social_links_check;
alter table public.profile_details add constraint profile_details_social_links_check
  check (jsonb_typeof(social_links) = 'object' and pg_column_size(social_links) <= 4000);

alter table public.profile_details drop constraint if exists profile_details_birth_date_check;
alter table public.profile_details add constraint profile_details_birth_date_check
  check (birth_date is null or birth_date >= date '1900-01-01');

alter table public.profile_details enable row level security;

drop policy if exists "People read their own details, user managers read all" on public.profile_details;
create policy "People read their own details, user managers read all"
  on public.profile_details for select to authenticated
  using (id = auth.uid() or public.user_has_cap('list_users'));

drop policy if exists "People add their own details" on public.profile_details;
create policy "People add their own details"
  on public.profile_details for insert to authenticated
  with check (id = auth.uid() or public.user_has_cap('edit_users'));

drop policy if exists "People update their own details" on public.profile_details;
create policy "People update their own details"
  on public.profile_details for update to authenticated
  using (id = auth.uid() or public.user_has_cap('edit_users'))
  with check (id = auth.uid() or public.user_has_cap('edit_users'));

drop policy if exists "People delete their own details" on public.profile_details;
create policy "People delete their own details"
  on public.profile_details for delete to authenticated
  using (id = auth.uid() or public.user_has_cap('edit_users'));

-- Anon has no policy, so RLS already returns nothing; this makes it explicit.
revoke all on table public.profile_details from anon;

notify pgrst, 'reload schema';

-- Appearance Ã¢â€ â€™ Theme Editor ----------------------------------------------------------------------
-- Kept identical to supabase/migrations/20260922_theme_editor.sql.
--
-- One row holds the whole theme: the block layout of the header, footer, sidebar, comments and
-- home/archive index (layout_structure), plus the raw code from each area's Code mode.
--
-- Everything here is rendered into public pages, so anyone may read it. Only manage_options
-- (administrators) may write it, because the code fields run in every visitor's browser,
-- including an administrator's: a lower role able to save a <script> could take over an
-- admin session.
--
-- Columns beyond the original spec, because each needs different sanitising:
--   custom_header_code   <head> tags only (script, noscript, link, meta), via scriptSanitizer.js
--   custom_header_html   markup shown in the header, via ContentRenderer's sanitizer
--   custom_footer_code   scripts added at the end of <body> (same allowlist as the <head> code)
--   custom_footer_html   markup shown in the footer
--   custom_sidebar_code  markup shown in the sidebar
--   custom_comments_css  CSS for the comments area, appended after custom_css

create table if not exists public.theme_settings (
  id uuid primary key default gen_random_uuid(),
  active_theme text not null default 'default',
  layout_structure jsonb not null default '{}'::jsonb,
  custom_header_code text not null default '',
  custom_footer_code text not null default '',
  custom_sidebar_code text not null default '',
  custom_css text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.theme_settings add column if not exists singleton boolean not null default true;
alter table public.theme_settings add column if not exists custom_header_html text not null default '';
alter table public.theme_settings add column if not exists custom_footer_html text not null default '';
alter table public.theme_settings add column if not exists custom_comments_css text not null default '';

-- Exactly one row: the theme is site-wide, and the app reads "the" row with limit 1.
alter table public.theme_settings drop constraint if exists theme_settings_singleton_check;
alter table public.theme_settings add constraint theme_settings_singleton_check check (singleton);
create unique index if not exists theme_settings_singleton_idx on public.theme_settings (singleton);

alter table public.theme_settings drop constraint if exists theme_settings_active_theme_check;
alter table public.theme_settings add constraint theme_settings_active_theme_check
  check (active_theme ~ '^[a-z0-9-]{1,64}$');

alter table public.theme_settings drop constraint if exists theme_settings_layout_check;
alter table public.theme_settings add constraint theme_settings_layout_check
  check (jsonb_typeof(layout_structure) = 'object' and pg_column_size(layout_structure) <= 512000);

-- Limits the size of every page response, since all of this is sent to every visitor.
alter table public.theme_settings drop constraint if exists theme_settings_code_length_check;
alter table public.theme_settings add constraint theme_settings_code_length_check check (
  char_length(custom_header_code) <= 100000
  and char_length(custom_header_html) <= 100000
  and char_length(custom_footer_code) <= 100000
  and char_length(custom_footer_html) <= 100000
  and char_length(custom_sidebar_code) <= 100000
  and char_length(custom_comments_css) <= 100000
  and char_length(custom_css) <= 200000
);

-- The editor saves with "where updated_at = <what I loaded>", so two administrators editing at
-- once get a conflict instead of silently overwriting each other. That needs the database, not
-- the browser, to set the timestamp.
create or replace function public.theme_settings_touch()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists theme_settings_touch on public.theme_settings;
create trigger theme_settings_touch
  before update on public.theme_settings
  for each row execute function public.theme_settings_touch();

insert into public.theme_settings (singleton) values (true) on conflict (singleton) do nothing;

alter table public.theme_settings enable row level security;

drop policy if exists "Anyone can read the theme" on public.theme_settings;
create policy "Anyone can read the theme"
  on public.theme_settings for select to anon, authenticated
  using (true);

drop policy if exists "Settings managers can add the theme" on public.theme_settings;
create policy "Settings managers can add the theme"
  on public.theme_settings for insert to authenticated
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Settings managers can update the theme" on public.theme_settings;
create policy "Settings managers can update the theme"
  on public.theme_settings for update to authenticated
  using (public.user_has_cap('manage_options'))
  with check (public.user_has_cap('manage_options'));

drop policy if exists "Settings managers can delete the theme" on public.theme_settings;
create policy "Settings managers can delete the theme"
  on public.theme_settings for delete to authenticated
  using (public.user_has_cap('manage_options'));

-- RLS already refuses anon writes; this makes it explicit.
revoke insert, update, delete on table public.theme_settings from anon;
grant select on table public.theme_settings to anon, authenticated;
grant insert, update, delete on table public.theme_settings to authenticated;

notify pgrst, 'reload schema';

-- Multilingual sites --------------------------------------------------------------------------
-- Kept identical to supabase/migrations/20260929_i18n_hooks.sql from this point on.

-- Multilingual sites: the four language options, and per-locale page content.
--
-- - public.options gains default_site_language, default_admin_language,
--   show_header_language_switcher and supported_languages. They live in `options` rather than
--   inside the rwp_app_settings document because the public site reads them before anything
--   else loads (src/lib/i18n.ts), and because options is already publicly readable.
-- - public.pages gains locale, translation_group_id and builder_data_i18n, so one page can hold
--   a Page Builder layout per language (correct ordering and spacing for LTR and RTL) and so
--   translations of the same page can find each other.
--
-- Values are stored as plain text, like every other option: booleans are 'true'/'false' and
-- supported_languages is a JSON array in a text column. option_value is `text`, not jsonb.
--
-- Safe to re-run.

-- 1. Language options -----------------------------------------------------------------------
-- on conflict do nothing: re-running must never overwrite what an administrator has chosen.

insert into public.options (option_name, option_value) values
  ('default_site_language', 'en'),
  ('default_admin_language', 'en'),
  ('show_header_language_switcher', 'true'),
  ('supported_languages', '["en"]')
on conflict (option_name) do nothing;

-- The site's language, for column defaults below. Falls back to 'en' when the option is missing
-- or was hand-edited to something empty. Deliberately NOT revoked from anon/authenticated: it is
-- used as a column default, which runs as the inserting user, and it only reads a public option.
create or replace function public.rwp_default_locale()
returns varchar(10) language sql stable security definer set search_path = public as $$
  select coalesce(
    nullif(trim(lower((select option_value from public.options where option_name = 'default_site_language'))), ''),
    'en'
  )::varchar(10);
$$;

-- 2. Per-language page content ---------------------------------------------------------------

alter table public.pages add column if not exists locale varchar(10);
alter table public.pages add column if not exists translation_group_id uuid;
alter table public.pages add column if not exists builder_data_i18n jsonb not null default '{}'::jsonb;

-- Existing rows predate multilingual support, so they are in whatever the site default is.
update public.pages set locale = public.rwp_default_locale() where locale is null;

-- Set after the backfill, so the default applies to new rows only.
alter table public.pages alter column locale set default public.rwp_default_locale();

-- A language tag, not free text: 'fa', 'en', 'pt-br'. Kept loose enough for regional codes.
alter table public.pages drop constraint if exists pages_locale_format;
alter table public.pages add constraint pages_locale_format
  check (locale is null or locale ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})?$');

-- builder_data_i18n maps a locale code to a builder document:
--   { "fa": { "version": 1, "settings": {…}, "content": […] } }
-- builder_data stays the layout for the page's own locale, so every existing page, every
-- renderer and every backup keeps working unchanged.
alter table public.pages drop constraint if exists pages_builder_data_i18n_object;
alter table public.pages add constraint pages_builder_data_i18n_object
  check (builder_data_i18n is null or jsonb_typeof(builder_data_i18n) = 'object');

create index if not exists pages_locale_idx on public.pages (locale);
create index if not exists pages_translation_group_idx on public.pages (translation_group_id)
  where translation_group_id is not null;

-- 3. Translation groups -----------------------------------------------------------------------
-- Two rows are translations of each other when they share a translation_group_id. The same
-- language must not appear twice in one group, or nothing could decide which row to show.

create unique index if not exists pages_translation_group_locale_key
  on public.pages (translation_group_id, locale)
  where translation_group_id is not null;

/*
 * Links p_page into the same translation group as p_translation_of, creating the group if the
 * other page has none yet. SECURITY INVOKER: the caller's own RLS decides whether they may
 * update both rows, exactly as a normal edit would.
 */
create or replace function public.rwp_link_translation(p_page bigint, p_translation_of bigint)
returns uuid language plpgsql security invoker set search_path = public as $$
declare
  v_group uuid;
  v_locale varchar(10);
  v_other_locale varchar(10);
begin
  if p_page = p_translation_of then
    raise exception 'A page cannot be a translation of itself.';
  end if;

  select locale, translation_group_id into v_locale, v_group from public.pages where id = p_page;
  if not found then
    raise exception 'Page % was not found, or your role cannot see it.', p_page;
  end if;

  select locale, coalesce(translation_group_id, v_group) into v_other_locale, v_group
  from public.pages where id = p_translation_of;
  if not found then
    raise exception 'Page % was not found, or your role cannot see it.', p_translation_of;
  end if;

  if v_locale is not distinct from v_other_locale then
    raise exception 'Both pages are in the same language (%), so neither is a translation of the other.', v_locale;
  end if;

  v_group := coalesce(v_group, gen_random_uuid());

  update public.pages set translation_group_id = v_group, updated_at = now()
  where id in (p_page, p_translation_of);

  -- An update RLS refused changes no rows and raises nothing, so it has to be checked.
  if not exists (select 1 from public.pages where id = p_page and translation_group_id = v_group) then
    raise exception 'The pages were not linked: your role cannot edit one of them.';
  end if;

  return v_group;
end;
$$;

revoke execute on function public.rwp_link_translation(bigint, bigint) from public, anon;
grant execute on function public.rwp_link_translation(bigint, bigint) to authenticated;

-- 4. Reload -------------------------------------------------------------------------------------
-- Without this PostgREST keeps serving the old column list and every new column reads as missing.

notify pgrst, 'reload schema';


notify pgrst, 'reload schema';
