create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  author_name text not null,
  author_email text not null,
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.options (
  option_name text primary key,
  option_value text not null
);

alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.options enable row level security;

drop policy if exists "Public can read published posts" on public.posts;
create policy "Public can read published posts"
  on public.posts for select to anon, authenticated
  using (status = 'published');

drop policy if exists "Authenticated users can manage posts" on public.posts;
drop policy if exists "Administrators and editors manage posts" on public.posts;
create policy "Administrators and editors manage posts"
  on public.posts for all to authenticated
  using ((auth.jwt() -> 'user_metadata' ->> 'role') in ('administrator', 'editor', 'super_admin'))
  with check ((auth.jwt() -> 'user_metadata' ->> 'role') in ('administrator', 'editor', 'super_admin'));

drop policy if exists "Authors and contributors manage own posts" on public.posts;
create policy "Authors and contributors manage own posts"
  on public.posts for all to authenticated
  using (
    author_id = auth.uid()
    and (auth.jwt() -> 'user_metadata' ->> 'role') in ('author', 'contributor')
  )
  with check (
    author_id = auth.uid()
    and (auth.jwt() -> 'user_metadata' ->> 'role') in ('author', 'contributor')
    and (
      (auth.jwt() -> 'user_metadata' ->> 'role') = 'author'
      or status = 'draft'
    )
  );

drop policy if exists "Authenticated users can manage comments" on public.comments;
create policy "Authenticated users can manage comments"
  on public.comments for all to authenticated
  using (true) with check (true);

drop policy if exists "Allow public read access on options" on public.options;
create policy "Allow public read access on options"
  on public.options for select using (true);

drop policy if exists "Allow authenticated full access on options" on public.options;
create policy "Allow authenticated full access on options"
  on public.options for all to authenticated
  using (true) with check (true);
