/**
 * Farsi for the English text visitors see that core, the default theme, the Page Builder's public
 * widgets and the shop write in code. The page translator (lib/pageTranslator.ts) matches rendered
 * text against these, so none of those components had to change.
 *
 * Keyed by the exact English text (whitespace collapsed). Fragments such as "to join the
 * discussion." exist because JSX splits a sentence around a link into separate text nodes.
 * Anything here can be reworded under Persian Origins → Site text or Settings → Translations:
 * a saved string beats a bundled one.
 *
 * Patterns (with {placeholders}) cover text built with values in it. A captured value is itself
 * translated when it matches a phrase, and dates and digits are localised separately.
 */

export const faPhrases: Array<[string, string]> = [
  // Header, navigation, account links -------------------------------------------------------------
  ['Home', 'خانه'],
  ['Blog', 'وبلاگ'],
  ['Log in', 'ورود'],
  ['Log In', 'ورود'],
  ['Log out', 'خروج'],
  ['Register', 'ثبت‌نام'],
  ['Sign in', 'ورود'],
  ['Sign out', 'خروج'],
  ['Dashboard', 'پیشخوان'],
  ['Admin dashboard', 'پیشخوان مدیریت'],
  ['Admin Dashboard', 'پیشخوان مدیریت'],
  ['Go to Admin Dashboard', 'رفتن به پیشخوان مدیریت'],
  ['Site admin', 'مدیریت سایت'],
  ['My account', 'حساب من'],
  ['My Account', 'حساب من'],
  ['Account', 'حساب کاربری'],
  ['Profile', 'نمایه'],
  ['User Profile', 'نمایهٔ کاربر'],
  ['Primary navigation', 'ناوبری اصلی'],
  ['Toggle navigation', 'باز و بسته کردن منو'],
  ['Main menu', 'منوی اصلی'],
  ['Open menu', 'باز کردن منو'],
  ['Close menu', 'بستن منو'],
  ['Menu', 'منو'],
  ['Navigation', 'ناوبری'],
  ['Skip to content', 'پرش به محتوا'],
  ['Change language', 'تغییر زبان'],
  ['Choose a language', 'یک زبان انتخاب کنید'],
  ['Language', 'زبان'],
  ['✎ Edit page', '✎ ویرایش برگه'],
  ['Edit page', 'ویرایش برگه'],
  ['View site', 'مشاهدهٔ سایت'],
  ['Exit preview', 'خروج از پیش‌نمایش'],
  ['Theme preview.', 'پیش‌نمایش پوسته.'],
  ['Signed in as', 'واردشده با'],

  // Search ----------------------------------------------------------------------------------------------
  ['Search', 'جستجو'],
  ['Search…', 'جستجو…'],
  ['Search posts…', 'جستجوی نوشته‌ها…'],
  ['Search results', 'نتایج جستجو'],
  ['Search results for:', 'نتایج جستجو برای:'],
  ['Searching…', 'در حال جستجو…'],
  ['No posts match your search.', 'هیچ نوشته‌ای با جستجوی شما مطابقت ندارد.'],
  ['Quick results are unavailable right now. Press Enter to search.', 'نتایج سریع اکنون در دسترس نیست. برای جستجو Enter را بزنید.'],
  ['Go', 'برو'],

  // Posts, pages, archives ---------------------------------------------------------------------------
  ['From the blog', 'از وبلاگ'],
  ['Page', 'برگه'],
  ['Post', 'نوشته'],
  ['Posts', 'نوشته‌ها'],
  ['Pages', 'برگه‌ها'],
  ['Read more', 'ادامهٔ مطلب'],
  ['Read More', 'ادامهٔ مطلب'],
  ['Read more →', 'ادامهٔ مطلب ←'],
  ['Load more', 'بارگذاری بیشتر'],
  ['Load more posts', 'بارگذاری نوشته‌های بیشتر'],
  ['Loading…', 'در حال بارگذاری…'],
  ['Please wait…', 'لطفاً صبر کنید…'],
  ['Redirecting…', 'در حال انتقال…'],
  ['No posts yet.', 'هنوز نوشته‌ای وجود ندارد.'],
  ['No posts found.', 'هیچ نوشته‌ای پیدا نشد.'],
  ['No posts on this page.', 'در این صفحه نوشته‌ای نیست.'],
  ['No posts match this query.', 'هیچ نوشته‌ای با این شرایط پیدا نشد.'],
  ['No pages yet.', 'هنوز برگه‌ای وجود ندارد.'],
  ['Nothing published yet.', 'هنوز چیزی منتشر نشده است.'],
  ['Nothing was found.', 'چیزی پیدا نشد.'],
  ['More posts could not be loaded.', 'نوشته‌های بیشتر بارگذاری نشدند.'],
  ['Unable to load posts.', 'بارگذاری نوشته‌ها ممکن نشد.'],
  ['Unable to load this page.', 'بارگذاری این برگه ممکن نشد.'],
  ['Could not load posts.', 'بارگذاری نوشته‌ها ممکن نشد.'],
  ['Could not load this content.', 'بارگذاری این محتوا ممکن نشد.'],
  ['Page not found', 'برگه پیدا نشد'],
  ['This page does not exist or is not published.', 'این برگه وجود ندارد یا منتشر نشده است.'],
  ['Return home', 'بازگشت به خانه'],
  ['← Newer posts', '→ نوشته‌های جدیدتر'],
  ['Older posts →', 'نوشته‌های قدیمی‌تر ←'],
  ['Newer posts', 'نوشته‌های جدیدتر'],
  ['Older posts', 'نوشته‌های قدیمی‌تر'],
  ['Previous posts', 'نوشته‌های قبلی'],
  ['Next posts', 'نوشته‌های بعدی'],
  ['Post pages', 'صفحه‌های نوشته‌ها'],
  ['Posts pages', 'صفحه‌های نوشته‌ها'],
  ['Previous', 'قبلی'],
  ['Next', 'بعدی'],
  ['← Previous', '→ قبلی'],
  ['Next →', 'بعدی ←'],
  ['Previous page', 'صفحهٔ قبل'],
  ['Next page', 'صفحهٔ بعد'],
  ['Previous slide', 'اسلاید قبلی'],
  ['Next slide', 'اسلاید بعدی'],
  ['Pagination', 'صفحه‌بندی'],
  ['Breadcrumb', 'مسیر راهنما'],
  ['Breadcrumbs', 'مسیر راهنما'],
  ['Archives', 'بایگانی‌ها'],
  ['Archives:', 'بایگانی:'],
  ['Category', 'دسته'],
  ['Category:', 'دسته:'],
  ['Categories', 'دسته‌ها'],
  ['Select category', 'انتخاب دسته'],
  ['All', 'همه'],
  ['All posts', 'همهٔ نوشته‌ها'],
  ['Tags', 'برچسب‌ها'],
  ['Author', 'نویسنده'],
  ['Author:', 'نویسنده:'],
  ['Unknown author', 'نویسندهٔ ناشناس'],
  ['this author', 'این نویسنده'],
  ['This page has no author.', 'این برگه نویسنده ندارد.'],
  ['This page has no excerpt yet.', 'این برگه هنوز خلاصه‌ای ندارد.'],
  ['There is no earlier or later published post.', 'نوشتهٔ منتشرشدهٔ قبلی یا بعدی وجود ندارد.'],
  ['Recent Posts', 'نوشته‌های تازه'],
  ['Recent posts', 'نوشته‌های تازه'],
  ['Latest posts', 'آخرین نوشته‌ها'],
  ['Recent Comments', 'دیدگاه‌های تازه'],
  ['Meta', 'اطلاعات'],
  ['Calendar', 'تقویم'],
  ['Sidebar', 'ستون کناری'],
  ['Footer', 'پانویس'],
  ['Header', 'سربرگ'],
  ['No categories yet.', 'هنوز دسته‌ای وجود ندارد.'],
  ['No categories have published posts yet.', 'هنوز هیچ دسته‌ای نوشتهٔ منتشرشده ندارد.'],
  ['No menu selected.', 'هیچ منویی انتخاب نشده است.'],
  ['This template is empty.', 'این قالب خالی است.'],
  ['Today', 'امروز'],
  ['Monday', 'دوشنبه'],
  ['Saturday', 'شنبه'],
  ['Sunday', 'یکشنبه'],

  // Default theme and default content -------------------------------------------------------------------
  ['Powered by React-WP & Supabase', 'قدرت‌گرفته از React-WP و Supabase'],
  ['A fresh start', 'یک شروع تازه'],
  ['This is your new React-WP website. Customize this homepage, publish your first post, and make it yours from the Admin Dashboard.',
    'این وب‌سایت تازهٔ React-WP شماست. این صفحهٔ اصلی را سفارشی کنید، نخستین نوشته‌تان را منتشر کنید و از پیشخوان مدیریت آن را از آنِ خود کنید.'],
  ['Be kind, stay on topic, and do not share personal information.', 'مهربان باشید، از موضوع خارج نشوید و اطلاعات شخصی منتشر نکنید.'],
  ['Hello World!', 'سلام دنیا!'],
  ['Welcome to React-WP. This is your first post. Edit or delete it, then start writing!', 'به React-WP خوش آمدید. این نخستین نوشتهٔ شماست. ویرایش یا حذفش کنید و نوشتن را آغاز کنید!'],
  ['Sample Page', 'برگهٔ نمونه'],
  ['Sample Post', 'نوشتهٔ نمونه'],
  ['Privacy Policy', 'حریم خصوصی'],
  ['Terms and Conditions', 'شرایط و قوانین'],
  ['Contact', 'تماس'],
  ['About', 'درباره'],
  ['Welcome', 'خوش آمدید'],
  ['Uncategorized', 'دسته‌بندی‌نشده'],
  ['Lost Password', 'فراموشی رمز عبور'],
  ['Facebook', 'فیس‌بوک'],
  ['Instagram', 'اینستاگرام'],
  ['LinkedIn', 'لینکدین'],
  ['YouTube', 'یوتیوب'],
  ['GitHub', 'گیت‌هاب'],

  // Comments --------------------------------------------------------------------------------------------------
  ['Comments', 'دیدگاه‌ها'],
  ['Comment pages', 'صفحه‌های دیدگاه‌ها'],
  ['No comments yet.', 'هنوز دیدگاهی ثبت نشده است.'],
  ['Comments are closed.', 'بخش دیدگاه‌ها بسته است.'],
  ['Join the discussion…', 'به گفت‌وگو بپیوندید…'],
  ['Write a comment', 'نوشتن دیدگاه'],
  ['Write a reply', 'نوشتن پاسخ'],
  ['Write a reply…', 'پاسخی بنویسید…'],
  ['Post comment', 'ارسال دیدگاه'],
  ['Post reply', 'ارسال پاسخ'],
  ['Posting…', 'در حال ارسال…'],
  ['Reply', 'پاسخ'],
  ['Cancel reply', 'لغو پاسخ'],
  ['Cancel', 'لغو'],
  ['Delete', 'حذف'],
  ['Edit', 'ویرایش'],
  ['Delete this comment and its replies?', 'این دیدگاه و پاسخ‌هایش حذف شوند؟'],
  ['Awaiting approval', 'در انتظار تأیید'],
  ['Comment posted.', 'دیدگاه ثبت شد.'],
  ['Thanks — your comment is awaiting approval.', 'سپاس — دیدگاه شما در انتظار تأیید است.'],
  ['to join the discussion.', 'تا به گفت‌وگو بپیوندید.'],
  ['Someone', 'یک کاربر'],

  // Sign in, register, lost password, profile -------------------------------------------------------------------
  ['Welcome back', 'خوش برگشتید'],
  ['Welcome back.', 'خوش برگشتید.'],
  ['Please sign in', 'لطفاً وارد شوید'],
  ['Create an account', 'ساخت حساب کاربری'],
  ['Create account', 'ساخت حساب'],
  ['Create one', 'یکی بسازید'],
  ['Join us', 'به ما بپیوندید'],
  ['Fill in your details to get started.', 'برای شروع، اطلاعاتتان را وارد کنید.'],
  ['Email', 'ایمیل'],
  ['Email address', 'نشانی ایمیل'],
  ['Password', 'رمز عبور'],
  ['New password', 'رمز عبور تازه'],
  ['Confirm new password', 'تکرار رمز عبور تازه'],
  ['Display name', 'نام نمایشی'],
  ['How your name appears on the site', 'نام شما در سایت این‌گونه نمایش داده می‌شود'],
  ['Forgot password?', 'رمز عبور را فراموش کرده‌اید؟'],
  ['No account yet?', 'هنوز حساب ندارید؟'],
  ['Already have an account?', 'حساب کاربری دارید؟'],
  ['Remembered it?', 'یادتان آمد؟'],
  ['Back to sign in', 'بازگشت به ورود'],
  ['or continue with', 'یا ادامه با'],
  ['Google', 'گوگل'],
  ['Continue', 'ادامه'],
  ['You are signed in', 'وارد شده‌اید'],
  ['Reset your password', 'بازنشانی رمز عبور'],
  ['Enter your email and we will send you a link to choose a new password.', 'ایمیلتان را وارد کنید تا پیوندی برای انتخاب رمز عبور تازه برایتان بفرستیم.'],
  ['Send reset link', 'ارسال پیوند بازنشانی'],
  ['Choose a new password', 'رمز عبور تازه‌ای انتخاب کنید'],
  ['Save new password', 'ذخیرهٔ رمز عبور تازه'],
  ['Your password has been changed.', 'رمز عبور شما تغییر کرد.'],
  ['The two passwords do not match.', 'دو رمز عبور یکسان نیستند.'],
  ['Registration is closed', 'ثبت‌نام بسته است'],
  ['Registration is currently closed.', 'ثبت‌نام در حال حاضر بسته است.'],
  ['This site is not accepting new accounts right now.', 'این سایت اکنون حساب تازه نمی‌پذیرد.'],
  ['Could not start the sign-in.', 'ورود آغاز نشد.'],
  ['Unable to sign in.', 'ورود ممکن نشد.'],
  ['Something went wrong.', 'مشکلی پیش آمد.'],
  ['Sign out of this site on this device.', 'در این دستگاه از سایت خارج شوید.'],
  ['Member', 'عضو'],
  ['· Member since', '· عضو از'],
  ['Member since', 'عضو از'],
  ['Administrator', 'مدیر'],
  ['Orders', 'سفارش‌ها'],
  ['Save changes', 'ذخیرهٔ تغییرات'],
  ['Save', 'ذخیره'],
  ['Saved.', 'ذخیره شد.'],
  ['Close', 'بستن'],
  ['Submit', 'ارسال'],
  ['Submitting…', 'در حال ارسال…'],
  ['Update', 'به‌روزرسانی'],
  ['View', 'مشاهده'],
  ['Remove', 'حذف'],
  ['Clear', 'پاک کردن'],
  ['Filter', 'پالایش'],
  ['Name', 'نام'],
  ['Message', 'پیام'],
  ['Phone', 'تلفن'],
  ['Title', 'عنوان'],
  ['Date', 'تاریخ'],
  ['Status', 'وضعیت'],
  ['Actions', 'کارها'],
  ['Description', 'توضیحات'],
  ['Details', 'جزئیات'],
  ['Image', 'تصویر'],
  ['Video', 'ویدیو'],
  ['Never', 'هرگز'],
  ['Yes', 'بله'],
  ['No', 'خیر'],
  ['Copy', 'رونوشت'],
  ['Copied!', 'رونوشت شد!'],
  // Supabase Auth's own messages, shown as they come back.
  ['Invalid login credentials', 'ایمیل یا رمز عبور نادرست است'],
  ['Email not confirmed', 'ایمیل هنوز تأیید نشده است'],
  ['User already registered', 'این ایمیل پیش‌تر ثبت شده است'],
  ['Password should be at least 6 characters.', 'رمز عبور باید دست‌کم ۶ نویسه باشد.'],
  ['Password should be at least 6 characters', 'رمز عبور باید دست‌کم ۶ نویسه باشد'],
  ['Unable to validate email address: invalid format', 'قالب نشانی ایمیل درست نیست'],
  ['Email rate limit exceeded', 'تعداد درخواست‌های ایمیل از حد مجاز گذشته است؛ کمی بعد دوباره تلاش کنید'],
  ['New password should be different from the old password.', 'رمز عبور تازه باید با رمز پیشین فرق داشته باشد.'],

  // Page Builder public widgets ------------------------------------------------------------------------------------
  ['Send message', 'ارسال پیام'],
  ['Sending…', 'در حال ارسال…'],
  ['Your name', 'نام شما'],
  ['How can we help?', 'چگونه می‌توانیم کمک کنیم؟'],
  ['Thanks! We will get back to you soon.', 'سپاس! به‌زودی با شما تماس می‌گیریم.'],
  ['Thanks! Your submission has been received.', 'سپاس! فرم شما دریافت شد.'],
  ['The form could not be sent.', 'فرم ارسال نشد.'],
  ['This form only works on a published page.', 'این فرم فقط در برگهٔ منتشرشده کار می‌کند.'],
  ['Choose…', 'انتخاب کنید…'],
  ['Learn more', 'بیشتر بدانید'],
  ['Get started', 'شروع کنید'],
  ['Click here', 'اینجا کلیک کنید'],
  ['Days', 'روز'],
  ['Hours', 'ساعت'],
  ['Minutes', 'دقیقه'],
  ['Seconds', 'ثانیه'],
  ['This offer has ended.', 'این پیشنهاد به پایان رسیده است.'],
  ['Table of Contents', 'فهرست مطالب'],
  ['Table of contents', 'فهرست مطالب'],
  ['Expand the table of contents', 'باز کردن فهرست مطالب'],
  ['Collapse the table of contents', 'بستن فهرست مطالب'],
  ['Tweet', 'توییت'],
  ['Current page', 'صفحهٔ کنونی'],
  ['Picture', 'تصویر'],

  // Shop --------------------------------------------------------------------------------------------------------------
  ['Shop', 'فروشگاه'],
  ['Products', 'محصولات'],
  ['Product', 'محصول'],
  ['Cart', 'سبد خرید'],
  ['View cart', 'مشاهدهٔ سبد خرید'],
  ['View cart →', 'مشاهدهٔ سبد خرید ←'],
  ['Checkout', 'تسویه‌حساب'],
  ['Add to cart', 'افزودن به سبد خرید'],
  ['Add to Cart', 'افزودن به سبد خرید'],
  ['Added to your cart.', 'به سبد خرید شما افزوده شد.'],
  ['Buy now', 'هم‌اکنون بخرید'],
  ['Buy product', 'خرید محصول'],
  ['Select options', 'انتخاب گزینه‌ها'],
  ['Choose an option', 'یک گزینه انتخاب کنید'],
  ['View products', 'مشاهدهٔ محصولات'],
  ['Browse products', 'مرور محصولات'],
  ['Return to shop', 'بازگشت به فروشگاه'],
  ['Return to the shop', 'بازگشت به فروشگاه'],
  ['← Back', '→ بازگشت'],
  ['Sale!', 'حراج!'],
  ['Sale price', 'قیمت حراج'],
  ['Original price', 'قیمت اصلی'],
  ['Price', 'قیمت'],
  ['Free', 'رایگان'],
  ['In stock', 'موجود'],
  ['Out of stock', 'ناموجود'],
  ['Available on backorder', 'قابل پیش‌سفارش'],
  ['Quantity', 'تعداد'],
  ['Subtotal', 'جمع جزء'],
  ['Tax', 'مالیات'],
  ['Shipping', 'ارسال'],
  ['Total', 'جمع کل'],
  ['Cart totals', 'جمع سبد خرید'],
  ['Proceed to checkout', 'ادامهٔ فرایند خرید'],
  ['Your cart is currently empty.', 'سبد خرید شما در حال حاضر خالی است.'],
  ['Your cart is empty.', 'سبد خرید شما خالی است.'],
  ['Your cart is empty, so there is nothing to check out.', 'سبد خرید شما خالی است، پس چیزی برای تسویه نیست.'],
  ['Coupon code', 'کد تخفیف'],
  ['Apply coupon', 'اعمال کد تخفیف'],
  ['Coupon:', 'کد تخفیف:'],
  ['Remove item', 'حذف کالا'],
  ['Calculate shipping', 'محاسبهٔ هزینهٔ ارسال'],
  ['Calculating…', 'در حال محاسبه…'],
  ['Shipping options will be shown once you enter your address.', 'گزینه‌های ارسال پس از وارد کردن نشانی نمایش داده می‌شوند.'],
  ['Billing details', 'جزئیات صورت‌حساب'],
  ['Billing address', 'نشانی صورت‌حساب'],
  ['Billing', 'صورت‌حساب'],
  ['Shipping address', 'نشانی ارسال'],
  ['Ship to a different address?', 'ارسال به نشانی دیگر؟'],
  ['First name', 'نام'],
  ['Last name', 'نام خانوادگی'],
  ['Company name', 'نام شرکت'],
  ['Company', 'شرکت'],
  ['Country / Region', 'کشور / منطقه'],
  ['Country', 'کشور'],
  ['Select a country / region…', 'انتخاب کشور / منطقه…'],
  ['Select a country…', 'انتخاب کشور…'],
  ['Street address', 'نشانی خیابان'],
  ['House number and street name', 'پلاک و نام خیابان'],
  ['Apartment, suite, etc.', 'واحد، طبقه و…'],
  ['Town / City', 'شهر'],
  ['State / County', 'استان'],
  ['State / county', 'استان'],
  ['Postcode / ZIP', 'کد پستی'],
  ['Order notes', 'یادداشت سفارش'],
  ['Notes about your order, e.g. special notes for delivery.', 'یادداشت دربارهٔ سفارش، مثلاً نکته‌های ویژهٔ تحویل.'],
  ['Your order', 'سفارش شما'],
  ['Payment method', 'روش پرداخت'],
  ['Place order', 'ثبت سفارش'],
  ['Placing order…', 'در حال ثبت سفارش…'],
  ['I have read and agree to the website', 'شرایط وب‌سایت را خوانده‌ام و می‌پذیرم:'],
  ['terms and conditions', 'شرایط و قوانین'],
  ['Returning customer?', 'پیش‌تر خرید کرده‌اید؟'],
  ['Click here to log in', 'برای ورود اینجا کلیک کنید'],
  ['You must be logged in to check out.', 'برای تسویه‌حساب باید وارد شوید.'],
  ['Sorry, no payment methods are available. Please contact us if you need help placing your order.', 'متأسفیم، هیچ روش پرداختی در دسترس نیست. اگر برای ثبت سفارش کمک می‌خواهید با ما تماس بگیرید.'],
  ['Thank you. Your order has been received.', 'سپاس. سفارش شما دریافت شد.'],
  ['Order received', 'سفارش دریافت شد'],
  ['Order', 'سفارش'],
  ['Order number', 'شمارهٔ سفارش'],
  ['Order details', 'جزئیات سفارش'],
  ['Order updates', 'به‌روزرسانی‌های سفارش'],
  ['Order not found', 'سفارش پیدا نشد'],
  ['Order not found.', 'سفارش پیدا نشد.'],
  ['View order', 'مشاهدهٔ سفارش'],
  ['Cancel order', 'لغو سفارش'],
  ['Cancel this order?', 'این سفارش لغو شود؟'],
  ['Pay', 'پرداخت'],
  ['Pay for this order', 'پرداخت این سفارش'],
  ['Payment reference', 'شناسهٔ پرداخت'],
  ['Our bank details', 'اطلاعات حساب بانکی ما'],
  ['Bank', 'بانک'],
  ['Account name', 'نام صاحب حساب'],
  ['Account number', 'شمارهٔ حساب'],
  ['IBAN', 'شبا'],
  ['Refunded', 'بازپرداخت شد'],
  ['Loading orders…', 'در حال بارگذاری سفارش‌ها…'],
  ['Loading products…', 'در حال بارگذاری محصولات…'],
  ['Loading your order…', 'در حال بارگذاری سفارش شما…'],
  ['No order has been made yet.', 'هنوز سفارشی ثبت نشده است.'],
  ['Downloads', 'دانلودها'],
  ['Download', 'دانلود'],
  ['Downloads remaining', 'دانلودهای باقی‌مانده'],
  ['Expires', 'انقضا'],
  ['No downloads available yet.', 'هنوز دانلودی در دسترس نیست.'],
  ['Addresses', 'نشانی‌ها'],
  ['Address changed successfully.', 'نشانی با موفقیت تغییر کرد.'],
  ['Save address', 'ذخیرهٔ نشانی'],
  ['Change address', 'تغییر نشانی'],
  ['You have not set up this address yet.', 'هنوز این نشانی را تنظیم نکرده‌اید.'],
  ['The following addresses will be used on the checkout page by default.', 'نشانی‌های زیر به‌طور پیش‌فرض در صفحهٔ تسویه‌حساب به کار می‌روند.'],
  ['Account details', 'جزئیات حساب'],
  ['Account details changed successfully.', 'جزئیات حساب با موفقیت تغییر کرد.'],
  ['Password change', 'تغییر رمز عبور'],
  ['The new passwords do not match.', 'رمزهای عبور تازه یکسان نیستند.'],
  ['Log in to see your orders, downloads and saved addresses.', 'برای دیدن سفارش‌ها، دانلودها و نشانی‌های ذخیره‌شده وارد شوید.'],
  ['Hello', 'سلام'],
  ['From your account dashboard you can view your', 'از پیشخوان حساب خود می‌توانید اینها را ببینید:'],
  ['recent orders', 'سفارش‌های اخیر'],
  ['shipping and billing addresses', 'نشانی‌های ارسال و صورت‌حساب'],
  ['edit your password and account details', 'ویرایش رمز عبور و جزئیات حساب'],
  ['view your orders', 'مشاهدهٔ سفارش‌ها'],
  ['was placed on', 'ثبت شد در'],
  ['and is currently', 'و اکنون در وضعیت'],
  ['Default sorting', 'مرتب‌سازی پیش‌فرض'],
  ['Sort by popularity', 'مرتب‌سازی بر اساس محبوبیت'],
  ['Sort by average rating', 'مرتب‌سازی بر اساس امتیاز'],
  ['Sort by latest', 'مرتب‌سازی بر اساس جدیدترین'],
  ['Sort by price: low to high', 'مرتب‌سازی بر اساس قیمت: ارزان به گران'],
  ['Sort by price: high to low', 'مرتب‌سازی بر اساس قیمت: گران به ارزان'],
  ['Sort products', 'مرتب‌سازی محصولات'],
  ['Search products', 'جستجوی محصولات'],
  ['Search products…', 'جستجوی محصولات…'],
  ['Filter by price', 'پالایش بر اساس قیمت'],
  ['Minimum price', 'کمترین قیمت'],
  ['Maximum price', 'بیشترین قیمت'],
  ['Min', 'کمینه'],
  ['Max', 'بیشینه'],
  ['On sale only', 'فقط حراجی‌ها'],
  ['Product categories', 'دسته‌های محصولات'],
  ['Product filters', 'پالایه‌های محصول'],
  ['No products found', 'محصولی پیدا نشد'],
  ['No products were found matching your selection.', 'محصولی مطابق انتخاب شما پیدا نشد.'],
  ['Product not found', 'محصول پیدا نشد'],
  ['This product does not exist or is not available.', 'این محصول وجود ندارد یا در دسترس نیست.'],
  ['Unavailable product', 'محصول ناموجود'],
  ['Sorry, this combination is unavailable. Please choose a different one.', 'متأسفیم، این ترکیب موجود نیست. لطفاً ترکیب دیگری انتخاب کنید.'],
  ['Additional information', 'اطلاعات بیشتر'],
  ['Additional Information', 'اطلاعات بیشتر'],
  ['Weight', 'وزن'],
  ['Dimensions', 'ابعاد'],
  ['No description.', 'بدون توضیحات.'],
  ['Reviews', 'نقد و بررسی‌ها'],
  ['There are no reviews yet.', 'هنوز نقدی ثبت نشده است.'],
  ['Add a review', 'افزودن نقد'],
  ['Your review', 'نقد شما'],
  ['Rating', 'امتیاز'],
  ['Please select a rating.', 'لطفاً یک امتیاز انتخاب کنید.'],
  ['Thank you for your review!', 'از نقد شما سپاسگزاریم!'],
  ['Thank you! Your review is awaiting approval.', 'سپاس! نقد شما در انتظار تأیید است.'],
  ['Your review could not be saved.', 'نقد شما ذخیره نشد.'],
  ['✓ Verified owner', '✓ خریدار تأییدشده'],
  ['You must be', 'باید'],
  ['logged in', 'وارد شوید'],
  ['to post a review.', 'تا نقدی بنویسید.'],
  ['Related products', 'محصولات مرتبط'],
  ['You may also like…', 'شاید این‌ها را هم بپسندید…'],
  ['You may be interested in…', 'شاید به این‌ها علاقه داشته باشید…'],
  ['Show image', 'نمایش تصویر'],
];

/** Text with values in it. {name} captures anything; the capture is translated too when it is a known phrase. */
export const faPatterns: Array<[string, string]> = [
  ['Nothing found for “{term}”.', 'چیزی برای «{term}» پیدا نشد.'],
  ['Search results for “{term}”', 'نتایج جستجو برای «{term}»'],
  ['Hello, {name}', 'سلام، {name}'],
  ['Hello {name}', 'سلام {name}'],
  ['Posts by {name}', 'نوشته‌های {name}'],
  ['Category: {name}', 'دسته: {name}'],
  ['Page {page} of {pages}', 'صفحهٔ {page} از {pages}'],
  ['{count} comments', '{count} دیدگاه'],
  ['{count} posts', '{count} نوشته'],
  ['({count})', '({count})'],
  ['© {year} {site}', '© {year} {site}'],
  ['For {email}. Use at least 6 characters.', 'برای {email}. دست‌کم ۶ نویسه به کار ببرید.'],
  ['If an account exists for {email}, a link to choose a new password is on its way. It opens this page.',
    'اگر حسابی با {email} وجود داشته باشد، پیوندی برای انتخاب رمز عبور تازه در راه است. آن پیوند همین صفحه را باز می‌کند.'],
  ['Account created. Check {email} for a confirmation link before signing in.',
    'حساب ساخته شد. پیش از ورود، پیوند تأیید را در {email} ببینید.'],
];
