import { registerPluginTranslations } from '../../../src/lib/i18n';

/**
 * The plugin's own interface strings. Registered with core, so they resolve through the same t()
 * as everything else and can be reworded under Settings → Translations like any core string.
 */
const en = {
  'po.switch.to': 'Switch to {language}',
  'po.switch.label': 'Language',
  'po.settings.open': 'Display settings',
  'po.settings.close': 'Close display settings',
  'po.settings.title': 'Display settings',
  'po.settings.theme': 'Theme',
  'po.settings.light': 'Light',
  'po.settings.dark': 'Dark',
  'po.settings.fontFor': '{language} font',
  'po.settings.textSize': 'Text size',
  'po.settings.smaller': 'Smaller text',
  'po.settings.larger': 'Larger text',
  'po.settings.reset': 'Reset',
  'po.settings.siteDefault': 'Site default',
  'po.categories.posts': '{count} posts',
  'po.categories.empty': 'No categories yet.',
  'po.categories.error': 'The categories could not be loaded.',
  'po.continue.start': 'Start reading',
  'po.continue.next': 'Continue reading: {title}',
  'po.continue.again': 'Read again from the start',
  'po.continue.empty': 'Nothing has been published in this category yet.',
  'po.continue.progress': '{read} of {total} read',
  'po.translator.start': 'Translate this page',
  'po.translator.done': 'Done translating',
  'po.translator.tip': 'Click any text to translate it. Esc to stop.',
  'po.translator.editorTitle': 'Translate this text',
  'po.translator.original': 'Original',
  'po.translator.into': 'In {language}',
  'po.translator.save': 'Save',
  'po.translator.resetButton': 'Reset',
  'po.translator.saved': 'Saved. Everywhere this text appears now shows the translation.',
  'po.translator.cleared': 'Saved as untranslated.',
  'po.translator.reset': 'Your translation was removed; the default one shows again.',
  'po.translator.hint': 'Applies everywhere this exact text appears. Ctrl+Enter saves.',
  'po.translator.pageBody': 'This is a translated page body. Edit it under Persian Origins → Pages & posts.',
  'po.translator.openAdmin': 'Open',
};

const fa: Record<keyof typeof en, string> = {
  'po.switch.to': 'تغییر به {language}',
  'po.switch.label': 'زبان',
  'po.settings.open': 'تنظیمات نمایش',
  'po.settings.close': 'بستن تنظیمات نمایش',
  'po.settings.title': 'تنظیمات نمایش',
  'po.settings.theme': 'پوسته',
  'po.settings.light': 'روشن',
  'po.settings.dark': 'تیره',
  'po.settings.fontFor': 'قلم {language}',
  'po.settings.textSize': 'اندازهٔ متن',
  'po.settings.smaller': 'متن کوچک‌تر',
  'po.settings.larger': 'متن بزرگ‌تر',
  'po.settings.reset': 'بازنشانی',
  'po.settings.siteDefault': 'پیش‌فرض سایت',
  'po.categories.posts': '{count} نوشته',
  'po.categories.empty': 'هنوز دسته‌ای وجود ندارد.',
  'po.categories.error': 'دسته‌ها بارگذاری نشدند.',
  'po.continue.start': 'شروع خواندن',
  'po.continue.next': 'ادامهٔ خواندن: {title}',
  'po.continue.again': 'خواندن دوباره از ابتدا',
  'po.continue.empty': 'هنوز نوشته‌ای در این دسته منتشر نشده است.',
  'po.continue.progress': '{read} از {total} خوانده شده',
  'po.translator.start': 'ترجمهٔ این صفحه',
  'po.translator.done': 'پایان ترجمه',
  'po.translator.tip': 'روی هر متنی کلیک کنید تا ترجمه‌اش کنید. برای توقف Esc را بزنید.',
  'po.translator.editorTitle': 'ترجمهٔ این متن',
  'po.translator.original': 'متن اصلی',
  'po.translator.into': 'به {language}',
  'po.translator.save': 'ذخیره',
  'po.translator.resetButton': 'بازنشانی',
  'po.translator.saved': 'ذخیره شد. هر جا این متن آمده باشد، ترجمه نمایش داده می‌شود.',
  'po.translator.cleared': 'به‌عنوان ترجمه‌نشده ذخیره شد.',
  'po.translator.reset': 'ترجمهٔ شما حذف شد؛ ترجمهٔ پیش‌فرض دوباره نمایش داده می‌شود.',
  'po.translator.hint': 'هر جا دقیقاً همین متن آمده باشد اعمال می‌شود. Ctrl+Enter ذخیره می‌کند.',
  'po.translator.pageBody': 'این متنِ ترجمه‌شدهٔ یک برگه است. آن را در Persian Origins ← برگه‌ها و نوشته‌ها ویرایش کنید.',
  'po.translator.openAdmin': 'باز کردن',
};

export const registerStrings = () => registerPluginTranslations('persian-origins', { en, fa });
