/**
 * Universal core schema, one dialect per backend.
 *
 * These are the tables the whole CMS needs to boot in any backend: the content model (pages,
 * posts, categories, menus, comments, media), the options key-value store, the plugin registry,
 * the singleton theme row (`theme_settings`), the translations catalogue (`rwp_translations`),
 * the optional per-person details (`profile_details`), the saved-items store (`bookmarks`), and
 * `rwp_users` for the universal auth engine. The Supabase backend keeps using the full
 * `supabase/schema.sql` (23 tables plus RLS policies, triggers and RPCs); these files are the
 * platform-agnostic equivalent that provisioning can run identically on PostgreSQL, MySQL and
 * SQLite.
 *
 * Every script is idempotent (`create table if not exists` / `create index if not exists`), so it
 * can be re-run against an existing database to add whatever it is missing without losing data.
 */
import type { DbType } from '../../runtime';

const pgSchema = /* sql */ `
create extension if not exists pgcrypto;

create table if not exists profiles (
  id text primary key,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'subscriber',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  author_id text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  is_post boolean not null default false,
  category_id uuid,
  featured_category_id uuid,
  posts_limit integer not null default 6,
  display_layout varchar(20) not null default 'grid',
  layout varchar(20) not null default 'boxed',
  show_sidebar boolean not null default false,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex boolean not null default false,
  og_title text,
  og_description text,
  og_image text,
  twitter_card varchar(30) not null default 'summary_large_image',
  comments_open boolean not null default true,
  meta_keywords text,
  author_id text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  page_id bigint,
  parent_id bigint,
  author_id text,
  author_name text,
  author_email text,
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamptz default now() not null
);

create table if not exists options (
  option_name text primary key,
  option_value text not null
);

create table if not exists menus (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  location text not null default 'primary',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists plugins (
  plugin_id text primary key,
  name text not null,
  version text not null,
  author text,
  description text default '',
  folder text,
  source text not null default 'bundled',
  active boolean not null default false,
  installed_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists media (
  id uuid primary key default gen_random_uuid(),
  title varchar(255),
  alt_text text,
  url text not null,
  provider varchar(50) not null default 'external',
  file_name varchar(255),
  provider_file_id text,
  width integer,
  height integer,
  bytes bigint,
  mime_type varchar(100),
  uploaded_by text,
  created_at timestamptz default now() not null,
  folder varchar(255) not null default 'general'
);

create table if not exists rwp_users (
  id text primary key,
  email text unique not null,
  password_hash text not null,
  role text not null default 'subscriber',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists theme_settings (
  id uuid primary key default gen_random_uuid(),
  singleton boolean not null default true,
  active_theme text not null default 'default',
  layout_structure jsonb not null default '{}'::jsonb,
  custom_header_code text not null default '',
  custom_header_html text not null default '',
  custom_footer_code text not null default '',
  custom_footer_html text not null default '',
  custom_sidebar_code text not null default '',
  custom_comments_css text not null default '',
  custom_css text not null default '',
  updated_at timestamptz default now() not null,
  constraint theme_settings_singleton_key unique (singleton)
);

create table if not exists profile_details (
  id text primary key,
  first_name text,
  last_name text,
  pronouns text,
  job_title text,
  company text,
  website text,
  location text,
  timezone text,
  phone text,
  birth_date text,
  social_links jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now() not null
);

create table if not exists rwp_translations (
  id uuid primary key default gen_random_uuid(),
  translation_key text not null,
  locale varchar(10) not null,
  translation_value text,
  source_text text,
  group_name varchar(50) not null default 'general',
  updated_by text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint rwp_translations_key_locale_key unique (translation_key, locale)
);

create index if not exists rwp_translations_locale_idx
  on rwp_translations (locale) where translation_value is not null;

create table if not exists bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  target_id text not null,
  target_type text not null,
  collection_name text not null default 'Saved Items',
  created_at timestamptz default now() not null,
  constraint bookmarks_user_target_collection_key unique (user_id, target_type, target_id, collection_name)
);

create index if not exists bookmarks_user_collection_idx
  on bookmarks (user_id, collection_name, created_at desc);
create index if not exists bookmarks_target_idx on bookmarks (target_type, target_id);

create table if not exists schema_migrations (
  name text primary key,
  applied_at timestamptz default now() not null
);
`;

const mysqlSchema = /* sql */ `
create table if not exists profiles (
  id varchar(191) primary key,
  email varchar(191),
  display_name varchar(255),
  avatar_url text,
  bio text,
  role varchar(20) not null default 'subscriber',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists posts (
  id bigint not null auto_increment primary key,
  title varchar(255) not null,
  slug varchar(255) not null,
  content longtext,
  excerpt text,
  status varchar(20) default 'draft',
  author_id varchar(191),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key posts_slug_unique (slug)
);

create table if not exists categories (
  id char(36) primary key default (uuid()),
  name varchar(255) not null,
  slug varchar(255) not null,
  description text,
  unique key categories_slug_unique (slug)
);

create table if not exists pages (
  id bigint not null auto_increment primary key,
  title varchar(255) not null,
  slug varchar(255) not null,
  content longtext,
  excerpt text,
  status varchar(20) default 'draft',
  is_post boolean not null default false,
  category_id char(36),
  featured_category_id char(36),
  posts_limit int not null default 6,
  display_layout varchar(20) not null default 'grid',
  layout varchar(20) not null default 'boxed',
  show_sidebar boolean not null default false,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex boolean not null default false,
  og_title text,
  og_description text,
  og_image text,
  twitter_card varchar(30) not null default 'summary_large_image',
  comments_open boolean not null default true,
  meta_keywords text,
  author_id varchar(191),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key pages_slug_unique (slug)
);

create table if not exists comments (
  id bigint not null auto_increment primary key,
  page_id bigint,
  parent_id bigint,
  author_id varchar(191),
  author_name varchar(255),
  author_email varchar(255),
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamp not null default current_timestamp
);

create table if not exists options (
  option_name varchar(191) primary key,
  option_value text not null
);

create table if not exists menus (
  id bigint not null auto_increment primary key,
  name varchar(255) not null,
  slug varchar(255) not null,
  location varchar(50) not null default 'primary',
  items json not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key menus_slug_unique (slug)
);

create table if not exists plugins (
  plugin_id varchar(191) primary key,
  name varchar(255) not null,
  version varchar(50) not null,
  author varchar(255),
  description text,
  folder varchar(255),
  source varchar(50) not null default 'bundled',
  active boolean not null default false,
  installed_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists media (
  id char(36) primary key default (uuid()),
  title varchar(255),
  alt_text text,
  url text not null,
  provider varchar(50) not null default 'external',
  file_name varchar(255),
  provider_file_id text,
  width int,
  height int,
  bytes bigint,
  mime_type varchar(100),
  uploaded_by varchar(191),
  created_at timestamp not null default current_timestamp,
  folder varchar(255) not null default 'general'
);

create table if not exists rwp_users (
  id varchar(191) primary key,
  email varchar(191) not null,
  password_hash varchar(255) not null,
  role varchar(20) not null default 'subscriber',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key rwp_users_email_unique (email)
);

create table if not exists theme_settings (
  id char(36) primary key default (uuid()),
  singleton boolean not null default true,
  active_theme varchar(64) not null default 'default',
  layout_structure json not null,
  custom_header_code mediumtext not null,
  custom_header_html mediumtext not null,
  custom_footer_code mediumtext not null,
  custom_footer_html mediumtext not null,
  custom_sidebar_code mediumtext not null,
  custom_comments_css mediumtext not null,
  custom_css mediumtext not null,
  updated_at timestamp not null default current_timestamp,
  unique key theme_settings_singleton_key (singleton)
);

create table if not exists profile_details (
  id varchar(191) primary key,
  first_name varchar(100),
  last_name varchar(100),
  pronouns varchar(40),
  job_title varchar(120),
  company varchar(120),
  website varchar(300),
  location varchar(120),
  timezone varchar(60),
  phone varchar(40),
  birth_date varchar(10),
  social_links json not null,
  updated_at timestamp not null default current_timestamp
);

create table if not exists rwp_translations (
  id char(36) primary key default (uuid()),
  translation_key varchar(191) not null,
  locale varchar(10) not null,
  translation_value mediumtext,
  source_text text,
  group_name varchar(50) not null default 'general',
  updated_by varchar(191),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key rwp_translations_key_locale_key (translation_key, locale),
  key rwp_translations_locale_idx (locale)
);

create table if not exists bookmarks (
  id char(36) primary key default (uuid()),
  user_id varchar(191) not null,
  target_id varchar(191) not null,
  target_type varchar(50) not null,
  collection_name varchar(191) not null default 'Saved Items',
  created_at timestamp not null default current_timestamp,
  unique key bookmarks_user_target_collection_key (user_id, target_type, target_id, collection_name),
  key bookmarks_user_collection_idx (user_id, collection_name, created_at),
  key bookmarks_target_idx (target_type, target_id)
);

create table if not exists schema_migrations (
  name varchar(191) primary key,
  applied_at timestamp not null default current_timestamp
);
`;

const sqliteSchema = /* sql */ `
create table if not exists profiles (
  id text primary key,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'subscriber',
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists posts (
  id integer primary key autoincrement,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status text default 'draft',
  author_id text,
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists categories (
  id text primary key default (lower(hex(randomblob(16)))),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists pages (
  id integer primary key autoincrement,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status text default 'draft',
  is_post integer not null default 0,
  category_id text,
  featured_category_id text,
  posts_limit integer not null default 6,
  display_layout text not null default 'grid',
  layout text not null default 'boxed',
  show_sidebar integer not null default 0,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex integer not null default 0,
  og_title text,
  og_description text,
  og_image text,
  twitter_card text not null default 'summary_large_image',
  comments_open integer not null default 1,
  meta_keywords text,
  author_id text,
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists comments (
  id integer primary key autoincrement,
  page_id integer,
  parent_id integer,
  author_id text,
  author_name text,
  author_email text,
  content text not null,
  status text default 'pending',
  created_at text not null default (datetime('now'))
);

create table if not exists options (
  option_name text primary key,
  option_value text not null
);

create table if not exists menus (
  id integer primary key autoincrement,
  name text not null,
  slug text unique not null,
  location text not null default 'primary',
  items text not null default '[]',
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists plugins (
  plugin_id text primary key,
  name text not null,
  version text not null,
  author text,
  description text default '',
  folder text,
  source text not null default 'bundled',
  active integer not null default 0,
  installed_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists media (
  id text primary key default (lower(hex(randomblob(16)))),
  title text,
  alt_text text,
  url text not null,
  provider text not null default 'external',
  file_name text,
  provider_file_id text,
  width integer,
  height integer,
  bytes integer,
  mime_type text,
  uploaded_by text,
  created_at text not null default (datetime('now')),
  folder text not null default 'general'
);

create table if not exists rwp_users (
  id text primary key,
  email text unique not null,
  password_hash text not null,
  role text not null default 'subscriber',
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create table if not exists theme_settings (
  id text primary key default (lower(hex(randomblob(16)))),
  singleton integer not null default 1,
  active_theme text not null default 'default',
  layout_structure text not null default '{}',
  custom_header_code text not null default '',
  custom_header_html text not null default '',
  custom_footer_code text not null default '',
  custom_footer_html text not null default '',
  custom_sidebar_code text not null default '',
  custom_comments_css text not null default '',
  custom_css text not null default '',
  updated_at text not null default (datetime('now')),
  unique (singleton)
);

create table if not exists profile_details (
  id text primary key,
  first_name text,
  last_name text,
  pronouns text,
  job_title text,
  company text,
  website text,
  location text,
  timezone text,
  phone text,
  birth_date text,
  social_links text not null default '{}',
  updated_at text not null default (datetime('now'))
);

create table if not exists rwp_translations (
  id text primary key default (lower(hex(randomblob(16)))),
  translation_key text not null,
  locale text not null,
  translation_value text,
  source_text text,
  group_name text not null default 'general',
  updated_by text,
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now')),
  unique (translation_key, locale)
);

create index if not exists rwp_translations_locale_idx
  on rwp_translations (locale) where translation_value is not null;

create table if not exists bookmarks (
  id text primary key default (lower(hex(randomblob(16)))),
  user_id text not null,
  target_id text not null,
  target_type text not null,
  collection_name text not null default 'Saved Items',
  created_at text not null default (datetime('now')),
  unique (user_id, target_type, target_id, collection_name)
);

create index if not exists bookmarks_user_collection_idx on bookmarks (user_id, collection_name, created_at);
create index if not exists bookmarks_target_idx on bookmarks (target_type, target_id);

create table if not exists schema_migrations (
  name text primary key,
  applied_at text not null default (datetime('now'))
);
`;

/** Returns the idempotent core schema for a backend, or the full Supabase schema for Supabase. */
export function schemaFor(dbType: DbType): string {
  switch (dbType) {
    case 'postgres':
      return pgSchema;
    case 'mysql':
      return mysqlSchema;
    case 'sqlite':
    case 'libsql':
      return sqliteSchema;
    case 'supabase':
      // The Supabase backend provisions through supabase/schema.sql (RLS + RPCs + triggers) via the
      // direct database connection, not through this platform-agnostic subset.
      return '';
    default:
      return pgSchema;
  }
}

export { pgSchema, mysqlSchema, sqliteSchema };


