-- React-WP universal core schema — PostgreSQL.
-- Idempotent: re-run to add whatever an existing database is missing. Supabase deployments keep
-- using supabase/schema.sql (RLS + RPCs + triggers); this is the platform-agnostic equivalent.

create extension if not exists pgcrypto;

create table if not exists profiles (
  id text primary key,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'subscriber',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  author_id text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft',
  is_post boolean not null default false,
  category_id uuid,
  featured_category_id uuid,
  posts_limit integer not null default 6,
  display_layout varchar(20) not null default 'grid',
  layout varchar(20) not null default 'boxed',
  show_sidebar boolean not null default false,
  seo_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  noindex boolean not null default false,
  og_title text,
  og_description text,
  og_image text,
  twitter_card varchar(30) not null default 'summary_large_image',
  comments_open boolean not null default true,
  meta_keywords text,
  author_id text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  page_id bigint,
  parent_id bigint,
  author_id text,
  author_name text,
  author_email text,
  content text not null,
  status varchar(20) default 'pending',
  created_at timestamptz default now() not null
);

create table if not exists options (
  option_name text primary key,
  option_value text not null
);

create table if not exists menus (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  location text not null default 'primary',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists plugins (
  plugin_id text primary key,
  name text not null,
  version text not null,
  author text,
  description text default '',
  folder text,
  source text not null default 'bundled',
  active boolean not null default false,
  installed_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists media (
  id uuid primary key default gen_random_uuid(),
  title varchar(255),
  alt_text text,
  url text not null,
  provider varchar(50) not null default 'external',
  file_name varchar(255),
  provider_file_id text,
  width integer,
  height integer,
  bytes bigint,
  mime_type varchar(100),
  uploaded_by text,
  created_at timestamptz default now() not null,
  folder varchar(255) not null default 'general'
);

create table if not exists rwp_users (
  id text primary key,
  email text unique not null,
  password_hash text not null,
  role text not null default 'subscriber',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists theme_settings (
  id uuid primary key default gen_random_uuid(),
  singleton boolean not null default true,
  active_theme text not null default 'default',
  layout_structure jsonb not null default '{}'::jsonb,
  custom_header_code text not null default '',
  custom_header_html text not null default '',
  custom_footer_code text not null default '',
  custom_footer_html text not null default '',
  custom_sidebar_code text not null default '',
  custom_comments_css text not null default '',
  custom_css text not null default '',
  updated_at timestamptz default now() not null,
  constraint theme_settings_singleton_key unique (singleton)
);

create table if not exists profile_details (
  id text primary key,
  first_name text,
  last_name text,
  pronouns text,
  job_title text,
  company text,
  website text,
  location text,
  timezone text,
  phone text,
  birth_date text,
  social_links jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now() not null
);

create table if not exists rwp_translations (
  id uuid primary key default gen_random_uuid(),
  translation_key text not null,
  locale varchar(10) not null,
  translation_value text,
  source_text text,
  group_name varchar(50) not null default 'general',
  updated_by text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint rwp_translations_key_locale_key unique (translation_key, locale)
);

create index if not exists rwp_translations_locale_idx
  on rwp_translations (locale) where translation_value is not null;

create table if not exists bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  target_id text not null,
  target_type text not null,
  collection_name text not null default 'Saved Items',
  created_at timestamptz default now() not null,
  constraint bookmarks_user_target_collection_key unique (user_id, target_type, target_id, collection_name)
);

create index if not exists bookmarks_user_collection_idx
  on bookmarks (user_id, collection_name, created_at desc);
create index if not exists bookmarks_target_idx on bookmarks (target_type, target_id);

create table if not exists schema_migrations (
  name text primary key,
  applied_at timestamptz default now() not null
);
