/**
 * The native SEO routes: /sitemap.xml and /robots.txt.
 *
 * Both are generated from the database on request rather than written to disk, because the thing
 * that changes them is publishing a post, and a file that has to be regenerated by a build step is
 * a file that is wrong between builds.
 *
 * Read with the publishable key, so PostgREST applies exactly the policies a visitor gets: there
 * is no privileged path here that could put a draft, a trashed post or another author's
 * unpublished work into a public sitemap. Rows marked noindex, and the Page Builder's site
 * template rows (which are pages rows but never have a URL of their own), are filtered out on top
 * of that.
 *
 * The result is held for the page cache's TTL. A crawler that asks every minute costs one query
 * per TTL, not one per visit.
 */
import { securitySettings } from './middleware/securitySettings.mjs';

const escapeXml = (value) => String(value ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&apos;');

const cache = { xml: '', builtAt: 0, origin: '' };

const get = async (config, path) => {
  const response = await fetch(`${config.supabaseUrl.replace(/\/$/, '')}/rest/v1/${path}`, {
    headers: { apikey: config.supabasePublishableKey, Authorization: `Bearer ${config.supabasePublishableKey}` },
  });
  if (!response.ok) throw new Error(`${path.split('?')[0]} returned HTTP ${response.status}`);
  return response.json();
};

/**
 * Published pages and posts. Tried with the full filter first; a site that has not run the site
 * templates migration has no is_site_template column and PostgREST rejects the whole query for it,
 * so the retry drops that one term rather than losing the sitemap entirely.
 */
const fetchEntries = async (config) => {
  const select = 'select=slug,updated_at,is_post,noindex&status=eq.published&order=updated_at.desc&limit=5000';
  try {
    return await get(config, `pages?${select}&is_site_template=is.false`);
  } catch {
    return get(config, `pages?${select}`);
  }
};

const fetchCategories = async (config) => {
  try {
    return await get(config, 'categories?select=slug&order=slug.asc&limit=1000');
  } catch {
    // A sitemap without category archives is still a useful sitemap.
    return [];
  }
};

const urlEntry = (loc, lastmod, changefreq, priority) => [
  '  <url>',
  `    <loc>${escapeXml(loc)}</loc>`,
  lastmod && `    <lastmod>${escapeXml(new Date(lastmod).toISOString().slice(0, 10))}</lastmod>`,
  `    <changefreq>${changefreq}</changefreq>`,
  `    <priority>${priority}</priority>`,
  '  </url>',
].filter(Boolean).join('\n');

/** Builds the XML. Throws only if the site is not installed; a query failure degrades to the home page. */
export async function buildSitemap(origin, config) {
  const settings = securitySettings();
  const cleanOrigin = origin.replace(/\/$/, '');
  const ttlMs = settings.cache_ttl_seconds * 1000;
  if (cache.xml && cache.origin === cleanOrigin && Date.now() - cache.builtAt < ttlMs) return cache.xml;

  let entries = [];
  let categories = [];
  if (config?.supabaseUrl && config?.supabasePublishableKey) {
    [entries, categories] = await Promise.all([
      fetchEntries(config).catch(() => []),
      fetchCategories(config),
    ]);
  }

  const published = (Array.isArray(entries) ? entries : []).filter((row) => row?.slug && row.noindex !== true);
  const newest = published[0]?.updated_at;

  const urls = [
    urlEntry(`${cleanOrigin}/`, newest, 'daily', '1.0'),
    ...published.map((row) => urlEntry(
      `${cleanOrigin}/${row.slug}`,
      row.updated_at,
      row.is_post ? 'weekly' : 'monthly',
      row.is_post ? '0.7' : '0.6',
    )),
    ...(Array.isArray(categories) ? categories : [])
      .filter((row) => row?.slug)
      .map((row) => urlEntry(`${cleanOrigin}/category/${row.slug}`, null, 'weekly', '0.4')),
  ];

  cache.xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;
  cache.builtAt = Date.now();
  cache.origin = cleanOrigin;
  return cache.xml;
}

export const purgeSitemap = () => {
  cache.xml = '';
  cache.builtAt = 0;
};

/**
 * robots.txt. An empty robots_txt_content means "use the generated default" rather than "serve an
 * empty file": a site whose administrator cleared the box by accident must not silently start
 * inviting crawlers into /admin.
 *
 * The admin, the page builder and the API are disallowed in both the default and, as a trailing
 * block, after custom content — an administrator can allow them back explicitly, but they never
 * disappear by omission. The sitemap line is appended unless the saved text already names one.
 */
export function buildRobots(origin) {
  const settings = securitySettings();
  const cleanOrigin = origin.replace(/\/$/, '');
  const custom = settings.robots_txt_content.trim();
  const sitemapLine = settings.sitemap_enabled ? `Sitemap: ${cleanOrigin}/sitemap.xml` : '';

  if (custom) {
    const hasSitemap = /^\s*sitemap\s*:/im.test(custom);
    return `${custom}\n${!hasSitemap && sitemapLine ? `\n${sitemapLine}\n` : ''}`;
  }

  return [
    'User-agent: *',
    'Disallow: /admin',
    'Disallow: /builder/',
    'Disallow: /api/',
    'Disallow: /login',
    'Disallow: /register',
    'Disallow: /lost-password',
    'Disallow: /profile',
    'Disallow: /dashboard',
    'Allow: /',
    '',
    sitemapLine,
    '',
  ].filter((line) => line !== undefined).join('\n');
}
