-- rwp-page-builder database schema.
-- Installed by the Plugins screen (POST /api/plugins/install-schema), never by
-- supabase/schema.sql. Safe to re-run.
--
-- pages.builder_data, pages.is_builder_enabled and pages.builder_data_i18n are NOT here:
-- they are core columns, because core's site templates and default content write them.

-- Page builder plugin (rwp-page-builder) -----------------------------------------------
-- Kept identical to supabase/migrations/20260918_page_builder.sql.

-- Columns and tables ----------------------------------------------------------------


create table if not exists public.elementor_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  type varchar(20) not null default 'section' check (type in ('page', 'section')),
  builder_data jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  form_id text not null,
  form_name text,
  -- Submissions outlive the page they came from.
  page_id bigint references public.pages(id) on delete set null,
  fields_data jsonb not null default '[]'::jsonb,
  status varchar(20) not null default 'new' check (status in ('new', 'read', 'spam')),
  email_status text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists form_submissions_page_idx on public.form_submissions(page_id, created_at desc);
create index if not exists form_submissions_form_idx on public.form_submissions(form_id, created_at desc);

create table if not exists public.page_builder_revisions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.pages(id) on delete cascade,
  builder_data jsonb not null,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists page_builder_revisions_page_idx on public.page_builder_revisions(page_id, created_at desc);

create table if not exists public.builder_form_settings (
  page_id bigint not null references public.pages(id) on delete cascade,
  form_id text not null,
  email_to text,
  email_subject text,
  updated_at timestamptz default timezone('utc'::text, now()) not null,
  primary key (page_id, form_id)
);

-- Helpers ----------------------------------------------------------------------------

-- Mirrors the pages update policy, so revisions and form settings follow page access.
create or replace function public.builder_can_edit_page(p_page_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.pages p
    where p.id = p_page_id
      and ((p.author_id = auth.uid() and public.user_has_cap('edit_posts'))
        or public.user_has_cap('edit_others_posts'))
  );
$$;

-- Every Custom HTML widget's code, as a jsonb array. Used to detect added or changed code.
create or replace function public.builder_html_fingerprint(p_data jsonb)
returns jsonb language sql immutable set search_path = public as $$
  select coalesce(jsonb_agg(distinct code), '[]'::jsonb)
  from (
    select coalesce(node -> 'settings' ->> 'html', '') || coalesce(node -> 'settings' ->> 'css', '')
      || coalesce(node -> 'settings' ->> 'js', '') as code
    from jsonb_path_query(coalesce(p_data, '{}'::jsonb), 'strict $.**') as node
    where jsonb_typeof(node) = 'object' and node ->> 'type' = 'html'
  ) widgets
  where code <> '';
$$;

create or replace function public.builder_guard_html()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  new_code jsonb := public.builder_html_fingerprint(new.builder_data);
  old_code jsonb := case when tg_op = 'UPDATE' then public.builder_html_fingerprint(old.builder_data) else '[]'::jsonb end;
begin
  -- auth.uid() is null for the installer and service-role connections.
  if auth.uid() is null or new_code = '[]'::jsonb or new_code <@ old_code then
    return new;
  end if;
  if not public.user_has_cap('manage_options') then
    raise exception 'Only administrators can add or change Custom HTML widgets, because their code runs in visitors'' browsers. Remove the Custom HTML widget (or undo your edit to it) and save again, or ask an administrator to make this change.'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists builder_guard_html_pages on public.pages;
create trigger builder_guard_html_pages
  before insert or update of builder_data on public.pages
  for each row execute function public.builder_guard_html();

drop trigger if exists builder_guard_html_templates on public.elementor_templates;
create trigger builder_guard_html_templates
  before insert or update of builder_data on public.elementor_templates
  for each row execute function public.builder_guard_html();

-- Revisions are written by a trigger, so every save is captured whichever screen made it.
create or replace function public.builder_record_revision()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.builder_data is null or new.builder_data is not distinct from old.builder_data then
    return new;
  end if;
  insert into public.page_builder_revisions (page_id, builder_data, author_id)
  values (new.id, new.builder_data, (select id from public.profiles where id = auth.uid()));
  -- Keep the 30 most recent revisions per page.
  delete from public.page_builder_revisions
  where page_id = new.id
    and id not in (
      select id from public.page_builder_revisions
      where page_id = new.id order by created_at desc, id desc limit 30
    );
  return new;
end;
$$;

drop trigger if exists builder_record_revision on public.pages;
create trigger builder_record_revision
  after update of builder_data on public.pages
  for each row execute function public.builder_record_revision();

create or replace function public.builder_templates_touch()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists builder_templates_touch on public.elementor_templates;
create trigger builder_templates_touch
  before update on public.elementor_templates
  for each row execute function public.builder_templates_touch();

-- Form submission ---------------------------------------------------------------------
-- The browser sends field values only. Which fields exist, which are required and which
-- choices are valid all come from the form widget saved in the published page.

create or replace function public.builder_submit_form(p_page_id bigint, p_form_id text, p_fields jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  page_row public.pages%rowtype;
  form_node jsonb;
  field jsonb;
  field_id text;
  field_type text;
  field_label text;
  raw jsonb;
  value text;
  choices jsonb;
  picked jsonb;
  errors jsonb := '{}'::jsonb;
  stored jsonb := '[]'::jsonb;
  submission_id uuid;
  recent integer;
  max_length integer;
begin
  if p_fields is null or jsonb_typeof(p_fields) <> 'object' then
    return jsonb_build_object('ok', false, 'error', 'The form data must be a JSON object of field values.');
  end if;
  if length(p_fields::text) > 60000 then
    return jsonb_build_object('ok', false, 'error', 'The form submission is too large.');
  end if;

  select * into page_row from public.pages
  where id = p_page_id and status = 'published' and is_builder_enabled;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'This form is not on a published page, so it cannot accept submissions.');
  end if;

  form_node := jsonb_path_query_first(
    coalesce(page_row.builder_data, '{}'::jsonb),
    'strict $.** ? (@.type == "form" && @.id == $id)',
    jsonb_build_object('id', p_form_id)
  );
  if form_node is null then
    return jsonb_build_object('ok', false, 'error', 'This form no longer exists on the page. Reload the page and try again.');
  end if;

  select count(*) into recent from public.form_submissions
  where page_id = p_page_id and form_id = p_form_id
    and created_at > timezone('utc'::text, now()) - interval '1 minute';
  if recent >= 20 then
    return jsonb_build_object('ok', false, 'error', 'This form is receiving too many submissions. Please try again in a minute.');
  end if;

  for field in select * from jsonb_array_elements(coalesce(form_node -> 'settings' -> 'fields', '[]'::jsonb)) loop
    field_id := field ->> 'id';
    field_type := coalesce(field ->> 'type', 'text');
    field_label := coalesce(nullif(field ->> 'label', ''), field_id);
    choices := case when jsonb_typeof(field -> 'options') = 'array' then field -> 'options' else '[]'::jsonb end;
    raw := p_fields -> field_id;
    continue when field_id is null;

    if field_type = 'checkbox' and jsonb_array_length(choices) > 0 then
      picked := case jsonb_typeof(raw) when 'array' then raw when 'string' then jsonb_build_array(raw) else '[]'::jsonb end;
      if exists (select 1 from jsonb_array_elements(picked) item where not choices @> jsonb_build_array(item)) then
        errors := errors || jsonb_build_object(field_id, 'Choose from the listed options.');
      elsif coalesce((field ->> 'required')::boolean, false) and jsonb_array_length(picked) = 0 then
        errors := errors || jsonb_build_object(field_id, format('%s is required.', field_label));
      end if;
      value := (select string_agg(item #>> '{}', ', ') from jsonb_array_elements(picked) item);
    elsif field_type = 'checkbox' then
      value := case when raw = 'true'::jsonb or raw #>> '{}' in ('true', 'on', '1', 'yes') then 'Yes' else 'No' end;
      if coalesce((field ->> 'required')::boolean, false) and value = 'No' then
        errors := errors || jsonb_build_object(field_id, format('%s must be checked.', field_label));
      end if;
    else
      value := btrim(coalesce(raw #>> '{}', ''));
      -- Not inlined into the elsif: PL/pgSQL ends an IF condition at the first THEN, including one inside CASE.
      max_length := case when field_type = 'textarea' then 5000 else 500 end;
      if coalesce((field ->> 'required')::boolean, false) and value = '' then
        errors := errors || jsonb_build_object(field_id, format('%s is required.', field_label));
      elsif length(value) > max_length then
        errors := errors || jsonb_build_object(field_id, format('%s is too long.', field_label));
      elsif value <> '' and field_type = 'email' and value !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
        errors := errors || jsonb_build_object(field_id, 'Enter a valid email address.');
      elsif value <> '' and field_type = 'select' and not choices @> jsonb_build_array(value) then
        errors := errors || jsonb_build_object(field_id, 'Choose one of the listed options.');
      end if;
    end if;

    stored := stored || jsonb_build_array(jsonb_build_object(
      'id', field_id, 'label', field_label, 'type', field_type, 'value', coalesce(value, '')));
  end loop;

  if errors <> '{}'::jsonb then
    return jsonb_build_object('ok', false, 'error', 'Please correct the highlighted fields.', 'errors', errors);
  end if;

  insert into public.form_submissions (form_id, form_name, page_id, fields_data)
  values (p_form_id, nullif(form_node -> 'settings' ->> 'form_name', ''), p_page_id, stored)
  returning id into submission_id;

  return jsonb_build_object(
    'ok', true,
    'id', submission_id,
    'message', coalesce(nullif(form_node -> 'settings' ->> 'success_message', ''), 'Thanks! Your submission has been received.'),
    'redirect_url', nullif(form_node -> 'settings' ->> 'redirect_url', ''),
    'send_email', coalesce(form_node -> 'settings' -> 'actions' ? 'email', false)
  );
end;
$$;

-- Author display names for Post Meta widgets. profiles itself is readable only when signed
-- in (it holds emails), so this returns names of people with published content, nothing else.
create or replace function public.builder_author_names(p_ids uuid[])
returns table (id uuid, display_name text) language sql stable security definer set search_path = public as $$
  select pr.id, coalesce(nullif(pr.display_name, ''), 'Author')
  from public.profiles pr
  where pr.id = any(p_ids)
    and exists (select 1 from public.pages pg where pg.author_id = pr.id and pg.status = 'published');
$$;

-- Widget pack (kept identical to supabase/migrations/20260923_builder_widgets.sql).
-- Visitors read a template only when a published builder page uses it, directly or through one
-- template that page uses. (Custom HTML in templates is guarded by builder_guard_html_templates.)
create or replace function public.builder_template_public(p_id uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select t.builder_data
  from public.elementor_templates t
  where t.id = p_id
    and (
      public.user_has_cap('edit_posts')
      or exists (
        select 1 from public.pages pg
        where pg.status = 'published' and pg.is_builder_enabled
          and position(p_id::text in coalesce(pg.builder_data::text, '')) > 0
      )
      or exists (
        select 1
        from public.elementor_templates parent
        join public.pages pg
          on pg.status = 'published' and pg.is_builder_enabled
          and position(parent.id::text in coalesce(pg.builder_data::text, '')) > 0
        where parent.id <> p_id
          and position(p_id::text in parent.builder_data::text) > 0
      )
    );
$$;

-- Author Box: name, avatar and bio of one page's author, for published pages or page editors.
create or replace function public.builder_author_profile(p_page_id bigint)
returns table (display_name text, avatar_url text, bio text)
language sql stable security definer set search_path = public as $$
  select coalesce(nullif(pr.display_name, ''), 'Author'), pr.avatar_url, pr.bio
  from public.pages pg
  join public.profiles pr on pr.id = pg.author_id
  where pg.id = p_page_id
    and (pg.status = 'published' or public.builder_can_edit_page(pg.id));
$$;

-- Row level security --------------------------------------------------------------------

alter table public.elementor_templates enable row level security;
alter table public.form_submissions enable row level security;
alter table public.page_builder_revisions enable row level security;
alter table public.builder_form_settings enable row level security;

drop policy if exists "Builders can read templates" on public.elementor_templates;
create policy "Builders can read templates"
  on public.elementor_templates for select to authenticated
  using (public.user_has_cap('edit_posts'));
drop policy if exists "Builders can create templates" on public.elementor_templates;
create policy "Builders can create templates"
  on public.elementor_templates for insert to authenticated
  with check (public.user_has_cap('edit_posts') and created_by = auth.uid());
drop policy if exists "Owners and editors update templates" on public.elementor_templates;
create policy "Owners and editors update templates"
  on public.elementor_templates for update to authenticated
  using ((created_by = auth.uid() and public.user_has_cap('edit_posts')) or public.user_has_cap('edit_others_posts'))
  with check (public.user_has_cap('edit_posts'));
drop policy if exists "Owners and editors delete templates" on public.elementor_templates;
create policy "Owners and editors delete templates"
  on public.elementor_templates for delete to authenticated
  using ((created_by = auth.uid() and public.user_has_cap('edit_posts')) or public.user_has_cap('edit_others_posts'));

-- No insert policy: submissions arrive only through builder_submit_form().
drop policy if exists "Page editors read form submissions" on public.form_submissions;
create policy "Page editors read form submissions"
  on public.form_submissions for select to authenticated
  using (public.user_has_cap('edit_pages'));
drop policy if exists "Page editors update form submissions" on public.form_submissions;
create policy "Page editors update form submissions"
  on public.form_submissions for update to authenticated
  using (public.user_has_cap('edit_pages')) with check (public.user_has_cap('edit_pages'));
drop policy if exists "Page editors delete form submissions" on public.form_submissions;
create policy "Page editors delete form submissions"
  on public.form_submissions for delete to authenticated
  using (public.user_has_cap('edit_pages'));

-- No insert policy: revisions are written by the builder_record_revision trigger.
drop policy if exists "Page editors read revisions" on public.page_builder_revisions;
create policy "Page editors read revisions"
  on public.page_builder_revisions for select to authenticated
  using (public.builder_can_edit_page(page_id));
drop policy if exists "Editors delete revisions" on public.page_builder_revisions;
create policy "Editors delete revisions"
  on public.page_builder_revisions for delete to authenticated
  using (public.user_has_cap('edit_others_posts'));

drop policy if exists "Page editors manage form settings" on public.builder_form_settings;
create policy "Page editors manage form settings"
  on public.builder_form_settings for all to authenticated
  using (public.builder_can_edit_page(page_id))
  with check (public.builder_can_edit_page(page_id));

-- Global colours and fonts live in the builder_global_styles option. Writing options needs
-- manage_options, which the existing "Settings managers can write options" policy covers.

-- Function privileges -------------------------------------------------------------------

revoke execute on function public.builder_guard_html() from public, anon, authenticated;
revoke execute on function public.builder_record_revision() from public, anon, authenticated;
revoke execute on function public.builder_templates_touch() from public, anon, authenticated;
revoke execute on function public.builder_html_fingerprint(jsonb) from public, anon, authenticated;

grant execute on function public.builder_can_edit_page(bigint) to anon, authenticated;
grant execute on function public.builder_submit_form(bigint, text, jsonb) to anon, authenticated;
grant execute on function public.builder_author_names(uuid[]) to anon, authenticated;
revoke execute on function public.builder_template_public(uuid) from public;
revoke execute on function public.builder_author_profile(bigint) from public;
grant execute on function public.builder_template_public(uuid) to anon, authenticated;
grant execute on function public.builder_author_profile(bigint) to anon, authenticated;

notify pgrst, 'reload schema';
