create extension if not exists pgcrypto;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text default '',
  excerpt text default '',
  status varchar(20) default 'draft' check (status in ('draft', 'published')),
  is_post boolean not null default false,
  category_id uuid references public.categories(id) on delete set null,
  featured_category_id uuid references public.categories(id) on delete set null,
  posts_limit integer not null default 6,
  display_layout varchar(20) not null default 'grid',
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;
alter table public.pages enable row level security;
drop policy if exists "Public can read published pages" on public.pages;
create policy "Public can read published pages" on public.pages for select to anon, authenticated using (status = 'published');
drop policy if exists "Authenticated users can manage pages" on public.pages;
create policy "Authenticated users can manage pages" on public.pages for all to authenticated using (true) with check (true);
drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories for select to anon, authenticated using (true);
drop policy if exists "Authenticated users can manage categories" on public.categories;
create policy "Authenticated users can manage categories" on public.categories for all to authenticated using (true) with check (true);

insert into public.pages (title, slug, content, excerpt, status, is_post, author_id, created_at, updated_at)
select title, slug, content, excerpt, status, true, author_id, created_at, updated_at
from public.posts
where not exists (select 1 from public.pages where pages.slug = posts.slug);
