// Vercel serverless entry point for the universal Hono API.
//
// `vercel.json` rewrites unmatched `/api/*` requests here. The hand-written file-system functions
// (`api/plugins.ts`, `api/media-delete.ts`, `api/imagekit-auth.ts`) still take precedence, and
// `api/install-schema.ts` is a second entry point onto this same bundle, so the routes below are all
// universal: `/api/install/*`, `/api/install-schema`, `/api/auth/*`, `/api/db/query`, `/api/media/*`
// and `/api/admin/plugins/upload-zip`.
//
// Import the pre-bundled JavaScript, never `../src/server/adapters/vercel.ts` or anything another
// `.ts` file re-exports: Vercel transpiles each API file on its own and keeps relative specifiers
// verbatim, so a TypeScript target shipped without a file extension and Node's native ESM resolver
// answered `ERR_MODULE_NOT_FOUND` for every request (`FUNCTION_INVOCATION_FAILED` in the browser).
// `npm run build:api` emits the whole Hono app as this single file, which `@vercel/nft` copies into
// the function bundle. It is the second half of `npm run build`, which is what `vercel.json`'s
// `buildCommand` runs, so the file exists on every path Vercel can take (a local `npm run build`,
// the project's default build command, a Git deploy).
// @ts-expect-error -- generated by `npm run build:api` (src/server-dist is git-ignored)
export { default } from '../src/server-dist/vercel.mjs';
