// Vercel serverless entry point for `POST /api/install-schema` — Step 5 of the Setup Wizard.
//
// The behaviour lives in the universal Hono app (`src/server/index.ts`), reached through the
// pre-bundled `../src/server-dist/vercel.mjs`, so every host provisions a site the same way.
//
// This file used to carry its own copy of the provisioning code, and that copy read the schema with
// `readFileSync(path.join(__dirname, '../supabase/schema.sql'))`. Two things were wrong with it:
//
//   * `"type": "module"` means there is no `__dirname`, and the array of candidate paths was built
//     eagerly, so the `ReferenceError` fired before the `process.cwd()` candidate beside it could be
//     tried. The wizard answered `Database setup failed: __dirname is not defined` on every Vercel
//     install, after the database connection had already succeeded.
//   * it only accepted `body.projectRef`, which the wizard never sends (it sends `supabaseUrl`,
//     `supabasePublishableKey` and `dbPassword`), so a wizard install without an explicit connection
//     string was rejected as "Project reference and database password … are required".
//
// The bundled app now inlines the schema (`vite.api.config.mjs` → `__RWP_SCHEMA_SQL__`), derives the
// Supabase host from the project URL, and answers with the environment Step 5 has to display. Keeping
// this re-export (instead of deleting the file) leaves `/api/install-schema` its own function, so the
// route does not depend on the `/api/(.*)` rewrite.
//
// Import the pre-bundled JavaScript, never `../src/server/adapters/vercel.ts`: Vercel transpiles each
// file under `api/` on its own and keeps relative specifiers verbatim, which Node's native ESM
// resolver cannot resolve (`FUNCTION_INVOCATION_FAILED`).
// @ts-expect-error -- generated by `npm run build:api` (src/server-dist is git-ignored)
export { default } from '../src/server-dist/vercel.mjs';
