import type { VercelRequest, VercelResponse } from '@vercel/node';
import { Client } from 'pg';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Expect database connection parameters
  const { dbConnectionString } = req.body || {};

  if (!dbConnectionString) {
    return res.status(400).json({ error: 'Missing Database Connection String.' });
  }

  const client = new Client({
    connectionString: dbConnectionString,
    ssl: { rejectUnauthorized: false },
  });

  try {
    await client.connect();

    const migrationSql = `
      CREATE TABLE IF NOT EXISTS public.posts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT UNIQUE NOT NULL,
        content TEXT DEFAULT '',
        excerpt TEXT DEFAULT '',
        status VARCHAR(20) DEFAULT 'draft',
        author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.comments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
        author_name TEXT NOT NULL,
        author_email TEXT NOT NULL,
        content TEXT NOT NULL,
        status VARCHAR(20) DEFAULT 'pending',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.options (
        option_name TEXT PRIMARY KEY,
        option_value TEXT NOT NULL
      );

      ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.options ENABLE ROW LEVEL SECURITY;
    `;

    await client.query(migrationSql);
    await client.end();

    return res.status(200).json({ success: true, message: 'Database tables created successfully.' });
  } catch (error: unknown) {
    await client.end().catch(() => {});
    const message = error instanceof Error ? error.message : 'Unknown database error';
    return res.status(500).json({ error: message });
  }
}