import type { VercelRequest, VercelResponse } from '@vercel/node';
import { Client } from 'pg';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { projectRef, serviceRoleKey } = req.body || {};

  if (!projectRef || !serviceRoleKey) {
    return res.status(400).json({ error: 'Missing Project Reference or Secret Key.' });
  }

  // Use Supabase Connection Pooler on Port 6543 to avoid port 5432 timeouts in serverless envs
  const client = new Client({
    host: `aws-0-eu-west-2.pooler.supabase.com`, // Global connection pooler host alias or project host
    port: 6543,
    database: 'postgres',
    user: `postgres.${projectRef}`,
    password: serviceRoleKey,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 15000,
  });

  const migrationSql = `
    CREATE TABLE IF NOT EXISTS public.posts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      content TEXT DEFAULT '',
      excerpt TEXT DEFAULT '',
      status VARCHAR(20) DEFAULT 'draft',
      author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS public.comments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
      author_name TEXT NOT NULL,
      author_email TEXT NOT NULL,
      content TEXT NOT NULL,
      status VARCHAR(20) DEFAULT 'pending',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS public.options (
      option_name TEXT PRIMARY KEY,
      option_value TEXT NOT NULL
    );

    ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.options ENABLE ROW LEVEL SECURITY;

    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'Authenticated users can manage posts'
      ) THEN
        CREATE POLICY "Authenticated users can manage posts" ON public.posts FOR ALL TO authenticated USING (true) WITH CHECK (true);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'comments' AND policyname = 'Authenticated users can manage comments'
      ) THEN
        CREATE POLICY "Authenticated users can manage comments" ON public.comments FOR ALL TO authenticated USING (true) WITH CHECK (true);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'options' AND policyname = 'Allow public read access on options'
      ) THEN
        CREATE POLICY "Allow public read access on options" ON public.options FOR SELECT USING (true);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'options' AND policyname = 'Allow authenticated full access on options'
      ) THEN
        CREATE POLICY "Allow authenticated full access on options" ON public.options FOR ALL TO authenticated USING (true) WITH CHECK (true);
      END IF;
    END
    $$;
  `;

  try {
    // Attempt Pooler connection
    await client.connect();
    await client.query(migrationSql);
    await client.end();

    return res.status(200).json({ success: true, message: 'Database tables created successfully.' });
  } catch (error: unknown) {
    await client.end().catch(() => {});
    
    // Fallback: If pooler host fails, attempt direct connection with project domain
    try {
      const fallbackClient = new Client({
        connectionString: `postgres://postgres.${projectRef}:${serviceRoleKey}@db.${projectRef}.supabase.co:5432/postgres`,
        ssl: { rejectUnauthorized: false },
        connectionTimeoutMillis: 15000,
      });

      await fallbackClient.connect();
      await fallbackClient.query(migrationSql);
      await fallbackClient.end();

      return res.status(200).json({ success: true, message: 'Database tables created via fallback.' });
    } catch (fallbackError: unknown) {
      const message = error instanceof Error ? error.message : 'Unknown connection failure';
      return res.status(500).json({ error: `Database setup connection timed out: ${message}` });
    }
  }
}