import type { VercelRequest, VercelResponse } from '@vercel/node';
import { Client } from 'pg';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const body = req.body || {};
  const projectRef = typeof body.projectRef === 'string' ? body.projectRef.trim() : '';
  const dbPassword = typeof body.dbPassword === 'string' ? body.dbPassword : '';
  const connectionString = typeof body.connectionString === 'string'
    ? body.connectionString.trim()
    : typeof body.databaseUrl === 'string'
      ? body.databaseUrl.trim()
      : '';
  const { saveSettings, siteTitle, adminEmail } = body;
  if ((!projectRef || !dbPassword) && !connectionString) {
    return res.status(400).json({ error: 'Project reference and database password, or a PostgreSQL connection string, are required.' });
  }

  const suppliedConnectionString = connectionString
    .replace(/\[(?:YOUR-)?PASSWORD\]/gi, encodeURIComponent(dbPassword))
    .replace(/<PASSWORD>/gi, encodeURIComponent(dbPassword));
  const client = new Client({
    connectionString: suppliedConnectionString || `postgres://postgres:${encodeURIComponent(dbPassword)}@db.${projectRef}.supabase.co:5432/postgres`,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 15000,
  });

  try {
    await client.connect();
    if (saveSettings) {
      if (!siteTitle || !adminEmail) {
        throw new Error('Site title and admin email are required.');
      }

      await client.query(
        `insert into public.options (option_name, option_value)
         values ($1, $2), ($3, $4), ($5, $6)
         on conflict (option_name) do update
         set option_value = excluded.option_value`,
        ['site_title', siteTitle, 'admin_email', adminEmail, 'installed', 'true'],
      );
      await client.query(
        `update auth.users
         set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object('role', 'administrator')
         where lower(email) = lower($1)`,
        [adminEmail],
      );
      await client.end();
      return res.status(200).json({ success: true });
    }

    await client.query(`
      create extension if not exists pgcrypto;
      create table if not exists public.categories (
        id uuid primary key default gen_random_uuid(),
        name text not null,
        slug text unique not null,
        description text
      );
      create table if not exists public.pages (
        id bigint generated by default as identity primary key,
        title text not null,
        slug text unique not null,
        content text default '',
        excerpt text default '',
        status varchar(20) default 'draft',
        is_post boolean not null default false,
        category_id uuid references public.categories(id) on delete set null,
        featured_category_id uuid references public.categories(id) on delete set null,
        posts_limit integer not null default 6,
        display_layout varchar(20) not null default 'grid',
        author_id uuid references auth.users(id) on delete set null,
        created_at timestamptz default timezone('utc'::text, now()) not null,
        updated_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.posts (
        id bigint generated by default as identity primary key,
        title text not null,
        slug text unique not null,
        content text default '',
        excerpt text default '',
        status varchar(20) default 'draft',
        author_id uuid references auth.users(id) on delete set null,
        created_at timestamptz default timezone('utc'::text, now()) not null,
        updated_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.comments (
        id bigint generated by default as identity primary key,
        post_id bigint references public.posts(id) on delete cascade,
        author_name text not null,
        author_email text not null,
        content text not null,
        status varchar(20) default 'pending',
        created_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.options (
        option_name text primary key,
        option_value text not null
      );
      create table if not exists public.menus (
        id bigint generated by default as identity primary key,
        name text not null,
        slug text unique not null,
        location text not null default 'primary',
        items jsonb not null default '[]'::jsonb,
        created_at timestamptz default timezone('utc'::text, now()) not null,
        updated_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.plugins (
        plugin_id text primary key,
        name text not null,
        version text not null,
        author text,
        description text default '',
        folder text,
        source text not null default 'bundled',
        active boolean not null default false,
        installed_at timestamptz default timezone('utc'::text, now()) not null,
        updated_at timestamptz default timezone('utc'::text, now()) not null
      );
      alter table public.posts enable row level security;
      alter table public.categories enable row level security;
      alter table public.pages enable row level security;
      alter table public.comments enable row level security;
      alter table public.options enable row level security;
      alter table public.menus enable row level security;
      alter table public.plugins enable row level security;
      drop policy if exists "Authenticated users can manage posts" on public.posts;
      create policy "Authenticated users can manage posts"
        on public.posts for all to authenticated using (true) with check (true);
      drop policy if exists "Public can read published pages" on public.pages;
      create policy "Public can read published pages" on public.pages for select to anon, authenticated using (status = 'published');
      drop policy if exists "Authenticated users can manage pages" on public.pages;
      create policy "Authenticated users can manage pages" on public.pages for all to authenticated using (true) with check (true);
      drop policy if exists "Public can read categories" on public.categories;
      create policy "Public can read categories" on public.categories for select to anon, authenticated using (true);
      drop policy if exists "Authenticated users can manage categories" on public.categories;
      create policy "Authenticated users can manage categories" on public.categories for all to authenticated using (true) with check (true);
      drop policy if exists "Authenticated users can manage comments" on public.comments;
      create policy "Authenticated users can manage comments"
        on public.comments for all to authenticated using (true) with check (true);
      drop policy if exists "Allow public read access on options" on public.options;
      create policy "Allow public read access on options"
        on public.options for select using (true);
      drop policy if exists "Allow authenticated full access on options" on public.options;
      create policy "Allow authenticated full access on options"
        on public.options for all to authenticated using (true) with check (true);
      drop policy if exists "Authenticated users can manage menus" on public.menus;
      create policy "Authenticated users can manage menus"
        on public.menus for all to authenticated using (true) with check (true);
      drop policy if exists "Authenticated users can manage plugins" on public.plugins;
      create policy "Authenticated users can manage plugins"
        on public.plugins for all to authenticated using (true) with check (true);
    `);
    await client.end();
    return res.status(200).json({ success: true });
  } catch (error: unknown) {
    await client.end().catch(() => {});
    const message = error instanceof Error ? error.message : 'Unknown database error';
    return res.status(500).json({ error: `Database setup failed: ${message}` });
  }
}
