import type { VercelRequest, VercelResponse } from '@vercel/node';
import { Client } from 'pg';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { projectRef, dbPassword, saveSettings, siteTitle, adminEmail } = req.body || {};
  if (!projectRef || !dbPassword) {
    return res.status(400).json({ error: 'Project reference and database password are required.' });
  }

  const client = new Client({
    connectionString: `postgres://postgres:${encodeURIComponent(dbPassword)}@db.${projectRef}.supabase.co:5432/postgres`,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 15000,
  });

  try {
    await client.connect();
    if (saveSettings) {
      if (!siteTitle || !adminEmail) {
        throw new Error('Site title and admin email are required.');
      }

      await client.query(
        `insert into public.options (option_name, option_value)
         values ($1, $2), ($3, $4), ($5, $6)
         on conflict (option_name) do update
         set option_value = excluded.option_value`,
        ['site_title', siteTitle, 'admin_email', adminEmail, 'installed', 'true'],
      );
      await client.end();
      return res.status(200).json({ success: true });
    }

    await client.query(`
      create table if not exists public.posts (
        id bigint generated by default as identity primary key,
        title text not null,
        slug text unique not null,
        content text default '',
        excerpt text default '',
        status varchar(20) default 'draft',
        author_id uuid references auth.users(id) on delete set null,
        created_at timestamptz default timezone('utc'::text, now()) not null,
        updated_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.comments (
        id bigint generated by default as identity primary key,
        post_id bigint references public.posts(id) on delete cascade,
        author_name text not null,
        author_email text not null,
        content text not null,
        status varchar(20) default 'pending',
        created_at timestamptz default timezone('utc'::text, now()) not null
      );
      create table if not exists public.options (
        option_name text primary key,
        option_value text not null
      );
      alter table public.posts enable row level security;
      alter table public.comments enable row level security;
      alter table public.options enable row level security;
      drop policy if exists "Authenticated users can manage posts" on public.posts;
      create policy "Authenticated users can manage posts"
        on public.posts for all to authenticated using (true) with check (true);
      drop policy if exists "Authenticated users can manage comments" on public.comments;
      create policy "Authenticated users can manage comments"
        on public.comments for all to authenticated using (true) with check (true);
      drop policy if exists "Allow public read access on options" on public.options;
      create policy "Allow public read access on options"
        on public.options for select using (true);
      drop policy if exists "Allow authenticated full access on options" on public.options;
      create policy "Allow authenticated full access on options"
        on public.options for all to authenticated using (true) with check (true);
    `);
    await client.end();
    return res.status(200).json({ success: true });
  } catch (error: unknown) {
    await client.end().catch(() => {});
    const message = error instanceof Error ? error.message : 'Unknown database error';
    return res.status(500).json({ error: `Database setup failed: ${message}` });
  }
}
